Mesh Smoothing Tool: myDataManager Class Reference
myDataManager Class Reference
The myDataManager class - data manager for mesh smoothing application.
#include <myDataManager.h>
Public Member Functions
myDataManager ()
myDataManager - default constructor
~myDataManager ()
myDataManager - destructor
void loadInputMesh (string &fileName)
loadInputMesh - load a mesh file supported by OpenMesh library
void saveOutputMesh (string &fileName)
saveOutputMesh - save the output mesh in a file supported bu OpenMesh library
void updateInputShape ()
updateInputShape - generate the corresponding shape data of the input mesh
void updateOutputShape ()
updateOutputShape - generate the corresponding shape data of the output mesh
void updateShapes ()
updateShapes - generate the corresponding shape data for both meshes (input mesh and output mesh)
void updateOutputSelection (vector< size_t > &indices)
updateOutputSelection - generate the selection shape for a set of given vertex indices
void setOutputAsInput ()
setOutputAsInput - set output mesh as input mesh (save all changes)
void reinitialize ()
reinitialize - set input mesh as output mesh (undone all changes)
Data Fields
TriMesh input_mesh
input_mesh - input mesh (left side in the interface)
TriMesh output_mesh
output_mesh - output mesh/resulting mesh/edited mesh (right side in the interface)
ShapeData input_mesh_shape
input_mesh_shape - input mesh shape data (for visualization)
ShapeData output_mesh_shape
output_mesh_shape - output mesh shape data (for visualization)
ShapeData selection
selection - shape data for current selection (set of vertices)
Detailed Description
The myDataManager class - data manager for mesh smoothing application.
Definition at line 10 of file myDataManager.h.
Constructor & Destructor Documentation
myDataManager()
myDataManager::myDataManager ()
myDataManager - default constructor
Definition at line 4 of file myDataManager.cpp.
 {
 }
~myDataManager()
myDataManager::~myDataManager ()
myDataManager - destructor
Definition at line 9 of file myDataManager.cpp.
References ShapeData::clear(), input_mesh, input_mesh_shape, output_mesh, output_mesh_shape, and selection.
 {
     input_mesh.clear();
     output_mesh.clear();
     input_mesh_shape.clear();
     output_mesh_shape.clear();
     selection.clear();
 }
Member Function Documentation
loadInputMesh()
void myDataManager::loadInputMesh (string & fileName)
loadInputMesh - load a mesh file supported by OpenMesh library
Parameters
fileName mesh file name
Definition at line 19 of file myDataManager.cpp.
References ShapeData::clear(), importMesh(), input_mesh, input_mesh_shape, output_mesh, and output_mesh_shape.
Referenced by myMainWindow::loadMesh().
 {
     input_mesh.clear();
     output_mesh.clear();
     input_mesh_shape.clear();
     output_mesh_shape.clear();
     importMesh(input_mesh, fileName);
     input_mesh.request_face_normals();
     input_mesh.request_vertex_normals();
     input_mesh.update_normals();
     output_mesh = input_mesh;
 }
reinitialize()
void myDataManager::reinitialize ()
reinitialize - set input mesh as output mesh (undone all changes)
Definition at line 72 of file myDataManager.cpp.
References input_mesh, output_mesh, and updateShapes().
Referenced by myMainWindow::reinitializeOutput().
 {
     output_mesh = input_mesh;
     updateShapes();
 }
saveOutputMesh()
void myDataManager::saveOutputMesh (string & fileName)
saveOutputMesh - save the output mesh in a file supported bu OpenMesh library
Parameters
fileName mesh file name
Definition at line 34 of file myDataManager.cpp.
References exportMesh(), and output_mesh.
Referenced by myMainWindow::saveMesh().
 {
     output_mesh.request_face_normals();
     output_mesh.request_vertex_normals();
     output_mesh.update_normals();
     exportMesh(output_mesh, fileName);
 }
setOutputAsInput()
void myDataManager::setOutputAsInput ()
setOutputAsInput - set output mesh as input mesh (save all changes)
Definition at line 66 of file myDataManager.cpp.
References input_mesh, output_mesh, and updateShapes().
Referenced by myMainWindow::setOutputAsInput().
 {
     input_mesh = output_mesh;
     updateShapes();
 }
updateInputShape()
void myDataManager::updateInputShape ()
updateInputShape - generate the corresponding shape data of the input mesh
Definition at line 42 of file myDataManager.cpp.
References ShapeData::clear(), input_mesh, input_mesh_shape, and ShapeData::loadMesh().
Referenced by updateShapes().
 {
     input_mesh_shape.clear();
     input_mesh_shape.loadMesh(input_mesh);
 }
updateOutputSelection()
void myDataManager::updateOutputSelection (vector< size_t > & indices)
updateOutputSelection - generate the selection shape for a set of given vertex indices
Parameters
indices target set of vertex indices
Definition at line 60 of file myDataManager.cpp.
References ShapeData::clear(), ShapeData::loadMeshVertexSelection(), output_mesh, and selection.
Referenced by myMainWindow::selectAndSmooth(), and myMainWindow::updateSelection().
 {
     selection.clear();
     selection.loadMeshVertexSelection(output_mesh, indices);
 }
updateOutputShape()
void myDataManager::updateOutputShape ()
updateOutputShape - generate the corresponding shape data of the output mesh
Definition at line 48 of file myDataManager.cpp.
References ShapeData::clear(), ShapeData::loadMesh(), output_mesh, and output_mesh_shape.
Referenced by myMainWindow::selectAndSmooth(), and updateShapes().
 {
     output_mesh_shape.clear();
     output_mesh_shape.loadMesh(output_mesh);
 }
updateShapes()
void myDataManager::updateShapes ()
updateShapes - generate the corresponding shape data for both meshes (input mesh and output mesh)
Definition at line 54 of file myDataManager.cpp.
References updateInputShape(), and updateOutputShape().
Referenced by myMainWindow::loadMesh(), reinitialize(), setOutputAsInput(), and myMainWindow::updateGlobalSmoothing().
 {
     updateInputShape();
     updateOutputShape();
 }
Field Documentation
input_mesh
TriMesh myDataManager::input_mesh
input_mesh - input mesh (left side in the interface)
Definition at line 16 of file myDataManager.h.
Referenced by loadInputMesh(), reinitialize(), setOutputAsInput(), updateInputShape(), and ~myDataManager().
input_mesh_shape
ShapeData myDataManager::input_mesh_shape
input_mesh_shape - input mesh shape data (for visualization)
Definition at line 25 of file myDataManager.h.
Referenced by loadInputMesh(), myMainWindow::loadMesh(), updateInputShape(), and ~myDataManager().
output_mesh
TriMesh myDataManager::output_mesh
output_mesh - output mesh/resulting mesh/edited mesh (right side in the interface)
Definition at line 20 of file myDataManager.h.
Referenced by myMainWindow::getSelection(), loadInputMesh(), reinitialize(), GlobalSmoothingTask::run(), saveOutputMesh(), myMainWindow::selectAndSmooth(), setOutputAsInput(), GlobalSmoothingTask::updateData(), updateOutputSelection(), updateOutputShape(), and ~myDataManager().
output_mesh_shape
ShapeData myDataManager::output_mesh_shape
output_mesh_shape - output mesh shape data (for visualization)
Definition at line 29 of file myDataManager.h.
Referenced by loadInputMesh(), myMainWindow::loadMesh(), updateOutputShape(), and ~myDataManager().
selection
ShapeData myDataManager::selection
selection - shape data for current selection (set of vertices)
Definition at line 34 of file myDataManager.h.
Referenced by myMainWindow::selectAndSmooth(), updateOutputSelection(), myMainWindow::updateSelection(), and ~myDataManager().
The documentation for this class was generated from the following files:
myDataManager.h
myDataManager.cpp