Mesh Smoothing Tool: myCamera Class Reference
myCamera Class Reference
Visualization based in OpenGL
The myCamera class - camera representation in a typical rendering pipeline (i.e. OpenGL)
#include <myCamera.h>
Public Member Functions
myCamera ()
myCamera - default constructor
void updateStrafeDirection ()
updateStrafeDirection - updates strafe direction vector given view direction and up vector
glm::mat4 getWorldToViewMatrix () const
getWorldToViewMatrix: generates world to view matrix
void moveForward ()
moveForward - moves camera position following view direction (regarding movement speed)
void moveBackward ()
moveBackward - moves camera position following the opposite direction of view direction (regarding movement speed)
void strafeLeft ()
strafeLeft - moves camera position following the opposite direction of strafe direction (regarding movement speed)
void strafeRight ()
strafeRight - moves camera position following the strafe direction (regarding movement speed)
void moveUp ()
moveUp - moves camera position following up direction (regarding movement speed)
void moveDown ()
moveDown - moves camera position following the opposite direction of up direction (regarding movement speed)
glm::vec3 getPosition () const
getPosition - get camera position
glm::vec3 getViewDirection () const
getViewDirection - get view direction
glm::vec3 getUP () const
getUP - get up direction
glm::vec3 getStrafeDirection () const
getStrafeDirection - get strafe direction
float getMovementSpeed () const
getMovementSpeed - get camera movement speed
void setPosition (glm::vec3 &_pos)
setPosition - set camera position
void setViewDirection (glm::vec3 &_viewDirection)
setViewDirection - set camera view direction
void setUp (glm::vec3 &_up)
setUp - set camera up direction
void setStrafeDirection (glm::vec3 &_strafeDirection)
setStrafeDirection - set strafe direction
void setMovementSpeed (float _movementSpeed)
setMovementSpeed - set camera movement speed
Private Attributes
glm::vec3 position
position - camera position in world space (eye)
glm::vec3 viewDirection
viewDirection - camera view direction (should be unit vector)
glm::vec3 up
up - camera up direction (should be unit vector)
glm::vec3 strafeDirection
strafeDirection - camera strafe direction (should be unit vector)
float movementSpeed
movementSpeed - movement speed for camera translation (forward, backward, left and right)
Detailed Description
The myCamera class - camera representation in a typical rendering pipeline (i.e. OpenGL)
Definition at line 19 of file myCamera.h.
Constructor & Destructor Documentation
myCamera()
myCamera::myCamera ()
myCamera - default constructor
Definition at line 3 of file myCamera.cpp.
References movementSpeed, and updateStrafeDirection().
                    :
 viewDirection(0.0f, 0.0f, -1.0f),
 position(0.f,0.f, 1.0f),
 up(0.0f, 1.0f, 0.0f)
 {
     updateStrafeDirection();
     movementSpeed = 1.0f;
 }
Member Function Documentation
getMovementSpeed()
float myCamera::getMovementSpeed () const inline
getMovementSpeed - get camera movement speed
Returns
camera movement speed value
Definition at line 106 of file myCamera.h.
Referenced by myRenderer::translateCamera().
 { return movementSpeed; }
getPosition()
glm::vec3 myCamera::getPosition () const inline
getPosition - get camera position
Returns
camera position vector
Definition at line 86 of file myCamera.h.
Referenced by myRenderer::draw(), myRenderer::getRayDirection(), myMainWindow::getSelection(), and myRenderer::translateCamera().
 { return position; }
getStrafeDirection()
glm::vec3 myCamera::getStrafeDirection () const inline
getStrafeDirection - get strafe direction
Returns
camera strafe direction vector
Definition at line 101 of file myCamera.h.
Referenced by myRenderer::translateCamera().
 { return strafeDirection; }
getUP()
glm::vec3 myCamera::getUP () const inline
getUP - get up direction
Returns
camera up direction vector
Definition at line 96 of file myCamera.h.
Referenced by myRenderer::getRayDirection(), and myRenderer::translateCamera().
 { return up; }
getViewDirection()
glm::vec3 myCamera::getViewDirection () const inline
getViewDirection - get view direction
Returns
camera view direction vector
Definition at line 91 of file myCamera.h.
Referenced by myRenderer::getRayDirection().
 { return viewDirection; }
getWorldToViewMatrix()
glm::mat4 myCamera::getWorldToViewMatrix () const
getWorldToViewMatrix: generates world to view matrix
Returns
4x4 world to view matrix
Definition at line 18 of file myCamera.cpp.
References position, up, and viewDirection.
Referenced by myRenderer::draw().
 {
     return glm::lookAt(position, position + viewDirection, up);
 }
moveBackward()
void myCamera::moveBackward ()
moveBackward - moves camera position following the opposite direction of view direction (regarding movement speed)
Definition at line 28 of file myCamera.cpp.
References movementSpeed, position, and viewDirection.
Referenced by myRenderer::zoom().
 {
     position += -movementSpeed * viewDirection;
 }
moveDown()
void myCamera::moveDown ()
moveDown - moves camera position following the opposite direction of up direction (regarding movement speed)
Definition at line 48 of file myCamera.cpp.
References movementSpeed, position, and up.
 {
     position += -movementSpeed * up;
 }
moveForward()
void myCamera::moveForward ()
moveForward - moves camera position following view direction (regarding movement speed)
Definition at line 23 of file myCamera.cpp.
References movementSpeed, position, and viewDirection.
Referenced by myRenderer::zoom().
 {
     position += movementSpeed * viewDirection;
 }
moveUp()
void myCamera::moveUp ()
moveUp - moves camera position following up direction (regarding movement speed)
Definition at line 43 of file myCamera.cpp.
References movementSpeed, position, and up.
 {
     position += movementSpeed * up;
 }
setMovementSpeed()
void myCamera::setMovementSpeed (float _movementSpeed) inline
setMovementSpeed - set camera movement speed
Parameters
_movementSpeed new camera movement speed
Definition at line 132 of file myCamera.h.
Referenced by myRenderer::initializeInteractor().
 { movementSpeed = _movementSpeed; }
setPosition()
void myCamera::setPosition (glm::vec3 & _pos) inline
setPosition - set camera position
Parameters
_pos new camera position
Definition at line 112 of file myCamera.h.
Referenced by myRenderer::initializeInteractor(), and myRenderer::translateCamera().
 { position = _pos; }
setStrafeDirection()
void myCamera::setStrafeDirection (glm::vec3 & _strafeDirection) inline
setStrafeDirection - set strafe direction
Parameters
_strafeDirection new camera strafe direction
Definition at line 127 of file myCamera.h.
 { strafeDirection = _strafeDirection; }
setUp()
void myCamera::setUp (glm::vec3 & _up) inline
setUp - set camera up direction
Parameters
_up new camera up direction
Definition at line 122 of file myCamera.h.
 { up = _up; }
setViewDirection()
void myCamera::setViewDirection (glm::vec3 & _viewDirection) inline
setViewDirection - set camera view direction
Parameters
_viewDirection new camera view direction
Definition at line 117 of file myCamera.h.
 { viewDirection = _viewDirection; }
strafeLeft()
void myCamera::strafeLeft ()
strafeLeft - moves camera position following the opposite direction of strafe direction (regarding movement speed)
Definition at line 33 of file myCamera.cpp.
References movementSpeed, position, and strafeDirection.
 {
     position += -movementSpeed * strafeDirection;
 }
strafeRight()
void myCamera::strafeRight ()
strafeRight - moves camera position following the strafe direction (regarding movement speed)
Definition at line 38 of file myCamera.cpp.
References movementSpeed, position, and strafeDirection.
 {
     position += movementSpeed * strafeDirection;
 }
updateStrafeDirection()
void myCamera::updateStrafeDirection ()
updateStrafeDirection - updates strafe direction vector given view direction and up vector
Definition at line 12 of file myCamera.cpp.
References strafeDirection, up, and viewDirection.
Referenced by myCamera().
 {
     strafeDirection = glm::cross(viewDirection, up);
     strafeDirection = glm::normalize(strafeDirection);
 }
Field Documentation
movementSpeed
float myCamera::movementSpeed private
movementSpeed - movement speed for camera translation (forward, backward, left and right)
Definition at line 41 of file myCamera.h.
Referenced by moveBackward(), moveDown(), moveForward(), moveUp(), myCamera(), strafeLeft(), and strafeRight().
position
glm::vec3 myCamera::position private
position - camera position in world space (eye)
Definition at line 24 of file myCamera.h.
Referenced by getWorldToViewMatrix(), moveBackward(), moveDown(), moveForward(), moveUp(), strafeLeft(), and strafeRight().
strafeDirection
glm::vec3 myCamera::strafeDirection private
strafeDirection - camera strafe direction (should be unit vector)
Definition at line 36 of file myCamera.h.
Referenced by strafeLeft(), strafeRight(), and updateStrafeDirection().
up
glm::vec3 myCamera::up private
up - camera up direction (should be unit vector)
Definition at line 32 of file myCamera.h.
Referenced by getWorldToViewMatrix(), moveDown(), moveUp(), and updateStrafeDirection().
viewDirection
glm::vec3 myCamera::viewDirection private
viewDirection - camera view direction (should be unit vector)
Definition at line 28 of file myCamera.h.
Referenced by getWorldToViewMatrix(), moveBackward(), moveForward(), and updateStrafeDirection().
The documentation for this class was generated from the following files:
visualization/myCamera.h
visualization/myCamera.cpp