Mesh Smoothing Tool: myRenderer Class Reference
myRenderer Class Reference
Visualization based on OpenGL
The myRenderer class - Renderer for multiple shapes (triangular meshes) visualization.
#include <myRenderer.h>
Public Member Functions
myRenderer ()
myRenderer - default constructor
virtual ~myRenderer ()
~myRenderer - destructor
void addShape (ShapeData *_sd)
addShape - add a shape (shape data) for rendering
void addShape (ShapeData *_sd, myDrawFlags _draw_mode)
addShape - add a shape (shape data) for rendering specifying its rendering mode
void setShapeDrawMode (size_t _shape_index, myDrawFlags _mode)
setShapeDrawMode - set rendering mode for a specific shape
void removeShape (size_t index)
removeShape - remove a shape
void addShader (GLenum _shaderType, const string &_fileName)
addShader - create and add a shader
void addShader (myShader *_shader)
addShader - add a shader
void clearShapes ()
clearShapes - erase shape containers without deleting pointers
void clearAndDeleteShapes ()
clearAndDeleteShapes - erate shape containers and delete items
void clearShaders ()
clearShaders - erase shader containers without deleting pointers
void clearAndDeleteShaders ()
clearAndDeleteShaders - erase shader containers and delete items
void createProgram ()
createProgram - create OpenGl program in the current context
bool installShaders ()
installShaders - compile and attach shaders to the main program (m_programID) in the current context
void sendDataSingleBuffer ()
sendDataSingleBuffer - send shape data to the GPU using OpenGL
void updateVertexBuffer (size_t index)
updateVertexBuffer - update and send vertex data for a single shape
void resendDataSingleBuffer ()
resendDataSingleBuffer - resend shape data to the GPU using OpenGL
void draw ()
draw - draw al shapes considering their rendering modes
void initialize ()
initialize - renderer initialization
void initializeInteractor ()
initializeInteractor - default initialization of renderer parameters based on shape data
void setDefaultValues ()
setDefaultValues - set custom renderer parameters
void computeCentralPoint ()
computeCentralPoint - compute the centroid of all points of all shapes
void computeBoundingSphereRadius ()
computeBoundingSphereRadius - compute the bounding sphere radius centered on the centroid of all points of all shapes
void rotateObjects (const glm::vec2 &newMousePosition)
rotateObjects - rotate all shapes (model to world matrix manipulation) regarding a mouse movement based interaction
void translateCamera (const glm::vec2 &newMousePosition)
translateCamera - translate all shapes (model to world matrix manipulation) regarding a mouse movement interaction
void zoom (float delta)
zoom - translate camera position (forward/backward) regarding a step size
GLuint getProgramID ()
getProgramID - get OpenGL program ID of renderer
GLsizeiptr getIndexOffsetAt (size_t pos)
getIndexOffsetAt - get indices offset for a shape
GLuint getVertexArrayObjectIDAt (size_t pos)
getVertexArrayObjectIDAt - get vertex array object ID (OpenGL) for a shape
size_t getNumberOfShapes ()
getNumberOfShapes - get the number of shapes contained in the renderer
glm::vec3 getRayDirection (glm::vec2 &pos)
getRayDirection - computation of the direction of a ray starting in camera position and ending in a point of the corresponding window contained in the near plane
GLuint getWidth ()
getters
GLuint getHeight ()
GLfloat getFOV ()
GLfloat getNear ()
GLfloat getFar ()
glm::mat4 getModelToWorldMatrix ()
glm::vec3 getSceneCentralPoint ()
float getBoundingSphereRadius ()
myCamera * getCamera ()
void setWidth (GLuint _width)
setters
void setHeight (GLuint _height)
void setFOV (GLfloat _fov)
void setNear (GLfloat _near)
void setFar (GLfloat _far)
void setModelToWorldMatrix (glm::mat4 &_modelToWorldMatrix)
void setSceneCentralPoint (glm::vec3 &_point)
void setBoundingSphereRadius (float _radius)
Private Attributes
GLuint m_width
Rendering.
GLuint m_height
m_height - window height
GLfloat m_fov
m_fov - field of view (FOV)
GLfloat m_near
m_near - near plane distance
GLfloat m_far
m_far - far plane distance
myCamera camera
camera - main camera for renderer
glm::vec4 light
light - main light "color"
glm::vec3 lightPosition
lightPosition - main light position
glm::mat4 modelToWorldMatrix
Interaction.
glm::vec2 oldMousePosition
oldMousePosition - old mouse position for mouse move interactions
glm::vec3 sceneCentralPoint
sceneCentralPoint - scene central point
float boundingSphereRadius
boundingSphereRadius - bounding sphere radius (regarding the central point)
GLuint m_programID
Data.
GLuint m_vertexBufferID
m_vertexBufferID - main vertex buffer ID
GLuint m_elementBufferID
m_elementBufferID - main element buffer ID
vector< myShader * > m_shaders
m_shaders - vector containing all shaders
vector< ShapeData * > m_shapes
m_shapes - vector containing all shapes
vector< GLsizeiptr > m_vertexOffsets
m_vertexOffsets - vector containing all shape vertices offsets
vector< GLsizeiptr > m_elementOffsets
m_elementOffsets - vector containing all shape indices offsets
vector< GLuint > m_vertexArrayObjectIDs
m_vertexArrayObjectIDs - vector containing all vertex array objects IDs
vector< myDrawFlags > m_draw_modes
m_draw_modes - vector containing all shape rendering modes
Detailed Description
The myRenderer class - Renderer for multiple shapes (triangular meshes) visualization.
Definition at line 34 of file myRenderer.h.
Constructor & Destructor Documentation
myRenderer()
myRenderer::myRenderer ()
myRenderer - default constructor
Definition at line 36 of file myRenderer.cpp.
References light, lightPosition, m_far, m_fov, m_height, m_near, m_width, modelToWorldMatrix, and sceneCentralPoint.
 {
     //currentDrawFlag = e_draw_faces;
     light = glm::vec4(0.1f,0.1f,0.1f,1.0f);
     lightPosition = glm::vec3(800.f, 800.f, 800.f);
     sceneCentralPoint = glm::vec3(0.0f, 0.0f, 0.0f);
     m_width = 1000;
     m_height = 800;
     m_fov = 45.0f;
     m_near = 1.0f;
     m_far = 1000.0f;
     modelToWorldMatrix = glm::translate(glm::vec3(0.0f, 0.0f, 0.0f));
 }
~myRenderer()
myRenderer::~myRenderer () virtual
~myRenderer - destructor
Definition at line 50 of file myRenderer.cpp.
References m_elementBufferID, m_programID, and m_vertexBufferID.
 {
     glDeleteBuffers(1, &m_vertexBufferID);
     glDeleteBuffers(1, &m_elementBufferID);
     glUseProgram(0);
     glDeleteProgram(m_programID);
 }
Member Function Documentation
addShader() [1/2]
void myRenderer::addShader (GLenum _shaderType, const string & _fileName)
addShader - create and add a shader
Parameters
_shaderType shader type
_fileName shader code file name
Definition at line 86 of file myRenderer.cpp.
References m_shaders, and myShader::readShaderCode().
Referenced by myGLWindow::addShader(), and myGLWindow::initializeGL().
 {
     myShader * t_ptr_shader = new myShader(_shaderType);
     t_ptr_shader->readShaderCode(_fileName);
     m_shaders.push_back(t_ptr_shader);
 }
addShader() [2/2]
void myRenderer::addShader (myShader * _shader)
addShader - add a shader
Parameters
_shader pointer to the shader
Definition at line 93 of file myRenderer.cpp.
References m_shaders.
 {
     m_shaders.push_back(_shader);
 }
addShape() [1/2]
void myRenderer::addShape (ShapeData * _sd)
addShape - add a shape (shape data) for rendering
Parameters
_sd shape data pointer to be added
Definition at line 58 of file myRenderer.cpp.
References e_draw_faces, m_draw_modes, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, and m_vertexOffsets.
Referenced by myGLWindow::setSelection(), and myGLWindow::setShape().
 {
     m_shapes.push_back(_sd);
     m_vertexOffsets.push_back(0);
     m_elementOffsets.push_back(0);
     m_vertexArrayObjectIDs.push_back(0);
     m_draw_modes.push_back(e_draw_faces);
 }
addShape() [2/2]
void myRenderer::addShape (ShapeData * _sd, myDrawFlags _draw_mode)
addShape - add a shape (shape data) for rendering specifying its rendering mode
Parameters
_sd shape data pointer to be added
_draw_mode rendering mode
Definition at line 67 of file myRenderer.cpp.
References m_draw_modes, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, and m_vertexOffsets.
 {
     m_shapes.push_back(_sd);
     m_vertexOffsets.push_back(0);
     m_elementOffsets.push_back(0);
     m_vertexArrayObjectIDs.push_back(0);
     m_draw_modes.push_back(_draw_mode);
 }
clearAndDeleteShaders()
void myRenderer::clearAndDeleteShaders ()
clearAndDeleteShaders - erase shader containers and delete items
Definition at line 135 of file myRenderer.cpp.
References m_programID, and m_shaders.
Referenced by myGLWindow::clearAndDeleteShaders().
 {
     for (size_t i = 0; i < m_shaders.size(); i++)
     {
         glDetachShader(m_programID,m_shaders[i]->getShaderID());
         delete m_shaders[i];
     }
     m_shaders.clear();
 }
clearAndDeleteShapes()
void myRenderer::clearAndDeleteShapes ()
clearAndDeleteShapes - erate shape containers and delete items
Definition at line 116 of file myRenderer.cpp.
References m_draw_modes, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, and m_vertexOffsets.
 {
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         glDeleteVertexArrays(1, &m_vertexArrayObjectIDs[i]);
         delete m_shapes[i];
     }
     m_shapes.clear();
     m_vertexOffsets.clear();
     m_elementOffsets.clear();
     m_vertexArrayObjectIDs.clear();
     m_draw_modes.clear();
 }
clearShaders()
void myRenderer::clearShaders ()
clearShaders - erase shader containers without deleting pointers
Definition at line 130 of file myRenderer.cpp.
References m_shaders.
 {
     m_shaders.clear();
 }
clearShapes()
void myRenderer::clearShapes ()
clearShapes - erase shape containers without deleting pointers
Definition at line 103 of file myRenderer.cpp.
References m_draw_modes, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, and m_vertexOffsets.
Referenced by myGLWindow::setShape().
 {
     for (size_t i = 0; i < m_vertexArrayObjectIDs.size(); i++)
     {
         glDeleteVertexArrays(1, &m_vertexArrayObjectIDs[i]);
     }
     m_shapes.clear();
     m_vertexOffsets.clear();
     m_elementOffsets.clear();
     m_vertexArrayObjectIDs.clear();
     m_draw_modes.clear();
 }
computeBoundingSphereRadius()
void myRenderer::computeBoundingSphereRadius ()
computeBoundingSphereRadius - compute the bounding sphere radius centered on the centroid of all points of all shapes
Definition at line 391 of file myRenderer.cpp.
References boundingSphereRadius, m_shapes, and sceneCentralPoint.
Referenced by initializeInteractor().
 {
     float max = 0.0f;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         for (size_t j = 0; j < m_shapes[i]->numVertices; j++)
         {
             glm::vec3 current_point = glm::vec3(m_shapes[i]->vertices[j].position.x, m_shapes[i]->vertices[j].position.y, m_shapes[i]->vertices[j].position.z);
             float dist = glm::distance(current_point,sceneCentralPoint);
             if (dist>max)
                 max = dist;
         }
     }
     boundingSphereRadius = max;
 }
computeCentralPoint()
void myRenderer::computeCentralPoint ()
computeCentralPoint - compute the centroid of all points of all shapes
Definition at line 376 of file myRenderer.cpp.
References m_shapes, and sceneCentralPoint.
Referenced by initializeInteractor().
 {
     float num = 0.0f;
     glm::vec3 t_sceneCentralPoint = glm::vec3(0.0f, 0.0f, 0.0f);
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         for (size_t j = 0; j < m_shapes[i]->numVertices; j++)
         {
             t_sceneCentralPoint += glm::vec3(m_shapes[i]->vertices[j].position.x,m_shapes[i]->vertices[j].position.y,m_shapes[i]->vertices[j].position.z);
             num += 1.0f;
         }
     }
     sceneCentralPoint = t_sceneCentralPoint/num;
 }
createProgram()
void myRenderer::createProgram ()
createProgram - create OpenGl program in the current context
Definition at line 145 of file myRenderer.cpp.
References m_programID.
Referenced by initialize().
 {
     m_programID = glCreateProgram();
 }
draw()
void myRenderer::draw ()
draw - draw al shapes considering their rendering modes
Definition at line 304 of file myRenderer.cpp.
References camera, e_draw_faces, e_draw_points, e_draw_selection, e_draw_wireframe, myCamera::getPosition(), myCamera::getWorldToViewMatrix(), light, lightPosition, m_draw_modes, m_elementOffsets, m_far, m_fov, m_height, m_near, m_programID, m_shapes, m_vertexArrayObjectIDs, m_width, and modelToWorldMatrix.
Referenced by myGLWindow::paintGL().
 {
     glViewport(0, 0, m_width, m_height);
     //glClearColor(0, 0, 0, 1);
     glClear(GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT);
     glm::mat4 modelToProjectionMatrix;
     glm::mat4 viewToProjectionMatrix = glm::perspective(m_fov, ((float)m_width) / ((float)(m_height)), m_near, m_far);
     glm::mat4 worldToViewMatrix = camera.getWorldToViewMatrix();
     glm::mat4 worldToProjectionMatrix = viewToProjectionMatrix * worldToViewMatrix;
     // 0: pointSize            1: not defined             2: not defined
     glm::vec3 aditionalProperties = glm::vec3(1.0f,0.0f,0.0f);
     GLuint fullTransformationUniformLocation;
     GLuint modelToWorldMatrixUniformLocation;
     GLuint lightUniformLocation;
     GLuint lightPositionUniformLocation;
     GLuint cameraPositionUniformLocation;
     GLuint aditionalPropertiesUniformLocation;
     fullTransformationUniformLocation = glGetUniformLocation(m_programID, "modelToProjectionMatrix");
     modelToWorldMatrixUniformLocation = glGetUniformLocation(m_programID, "modelToWorldMatrix");
     lightUniformLocation = glGetUniformLocation(m_programID, "lightVector");
     lightPositionUniformLocation = glGetUniformLocation(m_programID, "lightPositionVector");
     cameraPositionUniformLocation = glGetUniformLocation(m_programID, "cameraPositionVector");
     aditionalPropertiesUniformLocation = glGetUniformLocation(m_programID, "aditionalProperties");
     modelToProjectionMatrix = worldToProjectionMatrix * modelToWorldMatrix;
     glUniformMatrix4fv(fullTransformationUniformLocation, 1, GL_FALSE, &modelToProjectionMatrix[0][0]);
     glUniformMatrix4fv(modelToWorldMatrixUniformLocation, 1, GL_FALSE, &modelToWorldMatrix[0][0]);
     glUniform4fv(lightUniformLocation, 1, &light[0]);
     glUniform3fv(lightPositionUniformLocation, 1, &lightPosition[0]);
     glUniform3fv(cameraPositionUniformLocation, 1, &(camera.getPosition())[0]);
     glUniform3fv(aditionalPropertiesUniformLocation, 1, &aditionalProperties[0]);
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         glBindVertexArray(m_vertexArrayObjectIDs[i]);
         int currentDrawFlag = m_draw_modes[i];
         switch (currentDrawFlag)
         {
         case e_draw_faces:
             glDrawElements(GL_TRIANGLES, m_shapes[i]->numIndices, GL_UNSIGNED_INT, (void*)(m_elementOffsets[i]));
             break;
         case e_draw_wireframe:
             glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
             glDrawElements(GL_TRIANGLES, m_shapes[i]->numIndices, GL_UNSIGNED_INT, (void*)(m_elementOffsets[i]));
             glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
             break;
         case e_draw_points:
             glDrawArrays(GL_POINTS, 0, m_shapes[i]->numVertices);
             break;
         case e_draw_selection:
             aditionalProperties[0] = 3.0f;
             glUniform3fv(aditionalPropertiesUniformLocation, 1, &aditionalProperties[0]);
             glDrawArrays(GL_POINTS, 0, m_shapes[i]->numVertices);
             aditionalProperties[0] = 1.0f;
             break;
         }
         glBindVertexArray(0);
     }
 }
getBoundingSphereRadius()
float myRenderer::getBoundingSphereRadius () inline
Definition at line 196 of file myRenderer.h.
References boundingSphereRadius.
 {return boundingSphereRadius;}
getCamera()
myCamera* myRenderer::getCamera () inline
Definition at line 197 of file myRenderer.h.
References camera.
Referenced by myGLWindow::getCamera().
 {return &camera;}
getFar()
GLfloat myRenderer::getFar () inline
Definition at line 193 of file myRenderer.h.
References m_far.
 {return m_far;}
getFOV()
GLfloat myRenderer::getFOV () inline
Definition at line 191 of file myRenderer.h.
References m_fov.
 {return m_fov;}
getHeight()
GLuint myRenderer::getHeight () inline
Definition at line 190 of file myRenderer.h.
References m_height.
 {return m_height;}
getIndexOffsetAt()
GLsizeiptr myRenderer::getIndexOffsetAt (size_t pos) inline
getIndexOffsetAt - get indices offset for a shape
Parameters
pos index of the target shape
Returns
offset
Definition at line 167 of file myRenderer.h.
References m_elementOffsets.
 { return m_elementOffsets[pos]; }
getModelToWorldMatrix()
glm::mat4 myRenderer::getModelToWorldMatrix () inline
Definition at line 194 of file myRenderer.h.
References modelToWorldMatrix.
Referenced by myGLWindow::getModelToWorldMatrix().
 {return modelToWorldMatrix;}
getNear()
GLfloat myRenderer::getNear () inline
Definition at line 192 of file myRenderer.h.
References m_near.
 {return m_near;}
getNumberOfShapes()
size_t myRenderer::getNumberOfShapes () inline
getNumberOfShapes - get the number of shapes contained in the renderer
Returns
number of shapes
Definition at line 178 of file myRenderer.h.
References getRayDirection(), and m_shapes.
Referenced by myGLWindow::removeSelection(), myGLWindow::setSelection(), myGLWindow::setVisualizationMode(), and myGLWindow::updateMesh().
 { return m_shapes.size(); }
getProgramID()
GLuint myRenderer::getProgramID () inline
getProgramID - get OpenGL program ID of renderer
Returns
OpenGL porgram ID
Definition at line 161 of file myRenderer.h.
References m_programID.
 { return m_programID; }
getRayDirection()
glm::vec3 myRenderer::getRayDirection (glm::vec2 & pos)
getRayDirection - computation of the direction of a ray starting in camera position and ending in a point of the corresponding window contained in the near plane
Parameters
pos position in the window (contained in the near plane)
Returns
ray direction
Definition at line 460 of file myRenderer.cpp.
References camera, myCamera::getPosition(), myCamera::getUP(), myCamera::getViewDirection(), m_far, m_fov, m_height, m_near, and m_width.
Referenced by getNumberOfShapes(), and myGLWindow::getRayDirection().
 {
     float x = (2.0f * pos.x) / m_width - 1.0f;
     float y = 1.0f - (2.0f * pos.y) / m_height;
     float z = 1.0f;
     // normalised device space
     glm::vec3 ray_nds = glm::vec3(x, y, z);
     // clip space
     glm::vec4 ray_clip = glm::vec4(ray_nds.x, ray_nds.y, -1.0, 1.0);
     // eye space
     glm::mat4 proj_mat = glm::perspective(m_fov, ((float)m_width) / ((float)(m_height)), m_near, m_far);
     glm::mat4 view_mat = glm::lookAt(camera.getPosition(), camera.getPosition() + camera.getViewDirection(), camera.getUP());
     glm::vec4 ray_eye = inverse(proj_mat) * ray_clip;
     ray_eye = glm::vec4(ray_eye.x, ray_eye.y, -1.0, 0.0);
     // world space
     glm::vec3 ray_wor = glm::vec3(inverse(view_mat) * ray_eye);
     // don't forget to normalise the vector at some point
     ray_wor = glm::normalize(ray_wor);
     return ray_wor;
 }
getSceneCentralPoint()
glm::vec3 myRenderer::getSceneCentralPoint () inline
Definition at line 195 of file myRenderer.h.
References sceneCentralPoint.
 {return sceneCentralPoint;}
getVertexArrayObjectIDAt()
GLuint myRenderer::getVertexArrayObjectIDAt (size_t pos) inline
getVertexArrayObjectIDAt - get vertex array object ID (OpenGL) for a shape
Parameters
pos index of the target shape
Returns
vertex array object ID (OpenGL)
Definition at line 173 of file myRenderer.h.
References m_vertexArrayObjectIDs.
 { return m_vertexArrayObjectIDs[pos]; }
getWidth()
GLuint myRenderer::getWidth () inline
getters
Definition at line 189 of file myRenderer.h.
References m_width.
 {return m_width;}
initialize()
void myRenderer::initialize ()
initialize - renderer initialization
Definition at line 219 of file myRenderer.cpp.
References createProgram(), initializeInteractor(), installShaders(), and sendDataSingleBuffer().
Referenced by myGLWindow::initializeGL().
 {
     glewInit();
     glEnable(GL_DEPTH_TEST);
     glEnable(GL_VERTEX_PROGRAM_POINT_SIZE);
     createProgram();
     sendDataSingleBuffer();
     installShaders();
     initializeInteractor();
 }
initializeInteractor()
void myRenderer::initializeInteractor ()
initializeInteractor - default initialization of renderer parameters based on shape data
Definition at line 230 of file myRenderer.cpp.
References boundingSphereRadius, camera, computeBoundingSphereRadius(), computeCentralPoint(), sceneCentralPoint, myCamera::setMovementSpeed(), and myCamera::setPosition().
Referenced by initialize(), and setDefaultValues().
 {
     computeCentralPoint();
     computeBoundingSphereRadius();
     camera.setPosition(sceneCentralPoint+glm::vec3(0.0f,0.0f,2.0f*boundingSphereRadius));
     camera.setMovementSpeed(boundingSphereRadius/50.0f);
 }
installShaders()
bool myRenderer::installShaders ()
installShaders - compile and attach shaders to the main program (m_programID) in the current context
Returns
success
Definition at line 150 of file myRenderer.cpp.
References checkProgramStatus(), checkShaderStatus(), m_programID, and m_shaders.
Referenced by initialize(), and myGLWindow::installShaders().
 {
     for (size_t i = 0; i < m_shaders.size(); i++)
     {
         m_shaders[i]->createShader();
         m_shaders[i]->compileShader();
         if (!checkShaderStatus(m_shaders[i]->getShaderID())) return false;
         glAttachShader(m_programID, m_shaders[i]->getShaderID());
     }
     glLinkProgram(m_programID);
     if (!checkProgramStatus(m_programID)) return false;
     glUseProgram(m_programID);
     return true;
 }
removeShape()
void myRenderer::removeShape (size_t index)
removeShape - remove a shape
Parameters
index index of the target shape
Definition at line 76 of file myRenderer.cpp.
References m_draw_modes, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, and m_vertexOffsets.
Referenced by myGLWindow::removeSelection(), and myGLWindow::setSelection().
 {
     glDeleteVertexArrays(1, &m_vertexArrayObjectIDs[index]);
     m_shapes.erase(m_shapes.begin() + index);
     m_vertexOffsets.erase(m_vertexOffsets.begin() + index);
     m_elementOffsets.erase(m_elementOffsets.begin() + index);
     m_vertexArrayObjectIDs.erase(m_vertexArrayObjectIDs.begin() + index);
     m_draw_modes.erase(m_draw_modes.begin() + index);
 }
resendDataSingleBuffer()
void myRenderer::resendDataSingleBuffer ()
resendDataSingleBuffer - resend shape data to the GPU using OpenGL
Definition at line 251 of file myRenderer.cpp.
References m_elementBufferID, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, m_vertexBufferID, and m_vertexOffsets.
Referenced by myGLWindow::removeSelection(), myGLWindow::setSelection(), and myGLWindow::setShape().
 {
     const uint NUM_FLOATS_PER_VERTICE = 9;
     const uint VERTEX_BYTE_SIZE = NUM_FLOATS_PER_VERTICE * sizeof(float);
     GLsizeiptr totalVertexBufferSize = 0;
     GLsizeiptr totalElementBufferSize = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         totalVertexBufferSize += m_shapes[i]->vertexBufferSize();
         totalElementBufferSize += m_shapes[i]->indexBufferSize();
     }
     //glGenBuffers(1, &m_vertexBufferID);
     glBindBuffer(GL_ARRAY_BUFFER, m_vertexBufferID);
     glBufferData(GL_ARRAY_BUFFER, totalVertexBufferSize, 0, GL_DYNAMIC_DRAW);
     GLsizeiptr currentVertexOffset = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         m_vertexOffsets[i] = currentVertexOffset;
         glBufferSubData(GL_ARRAY_BUFFER, currentVertexOffset, m_shapes[i]->vertexBufferSize(), m_shapes[i]->vertices);
         currentVertexOffset += m_shapes[i]->vertexBufferSize();
     }
     //glGenBuffers(1, &m_elementBufferID);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_elementBufferID);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, totalElementBufferSize, 0, GL_STATIC_DRAW);
     GLsizeiptr currentElementOffset = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         m_elementOffsets[i] = currentElementOffset;
         glBufferSubData(GL_ELEMENT_ARRAY_BUFFER, currentElementOffset, m_shapes[i]->indexBufferSize(), m_shapes[i]->indices);
         currentElementOffset += m_shapes[i]->indexBufferSize();
     }
     //cout << "vertex buffer : "<< m_vertexBufferID << endl;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         glGenVertexArrays(1, &m_vertexArrayObjectIDs[i]);
         glBindVertexArray(m_vertexArrayObjectIDs[i]);
         //cout << m_vertexArrayObjectIDs[i] << endl;
         glEnableVertexAttribArray(0);
         glEnableVertexAttribArray(1);
         glEnableVertexAttribArray(2);
         glBindBuffer(GL_ARRAY_BUFFER, m_vertexBufferID);
         glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i]));
         glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i] + sizeof(float)* 3));
         glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i] + sizeof(float)* 6));
         glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_elementBufferID);
     }
 }
rotateObjects()
void myRenderer::rotateObjects (const glm::vec2 & newMousePosition)
rotateObjects - rotate all shapes (model to world matrix manipulation) regarding a mouse movement based interaction
Parameters
newMousePosition current mouse position
Definition at line 408 of file myRenderer.cpp.
References modelToWorldMatrix, oldMousePosition, and sceneCentralPoint.
Referenced by myGLWindow::event().
 {
     glm::vec2 mouseDelta = newMousePosition - oldMousePosition;
     if (glm::length(mouseDelta) > 20.0f || glm::length(mouseDelta) < 1.0f)
     {
         oldMousePosition = newMousePosition;
         return;
     }
     const float ROTATIONAL_SPEED = 0.1f;
     float valx = mouseDelta.x * ROTATIONAL_SPEED;
     float valy = mouseDelta.y * ROTATIONAL_SPEED;
     glm::mat4 transform = glm::translate(glm::vec3(-sceneCentralPoint.x, -sceneCentralPoint.y, -sceneCentralPoint.z));
     glm::mat4 rotator = glm::rotate(valx, glm::vec3(0.0f,1.0f,0.0f)) * glm::rotate(valy, glm::vec3(1.0f,0.0f,0.0f));
     transform = rotator*transform;
     glm::mat4 temp = translate(glm::vec3(sceneCentralPoint.x, sceneCentralPoint.y, sceneCentralPoint.z));
     transform = temp * transform;
     modelToWorldMatrix = transform * modelToWorldMatrix;
     oldMousePosition = newMousePosition;
     return;
 }
sendDataSingleBuffer()
void myRenderer::sendDataSingleBuffer ()
sendDataSingleBuffer - send shape data to the GPU using OpenGL
Definition at line 165 of file myRenderer.cpp.
References m_elementBufferID, m_elementOffsets, m_shapes, m_vertexArrayObjectIDs, m_vertexBufferID, and m_vertexOffsets.
Referenced by initialize(), and myGLWindow::sendDataToOpenGL().
 {
     const uint NUM_FLOATS_PER_VERTICE = 9;
     const uint VERTEX_BYTE_SIZE = NUM_FLOATS_PER_VERTICE * sizeof(float);
     GLsizeiptr totalVertexBufferSize = 0;
     GLsizeiptr totalElementBufferSize = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         totalVertexBufferSize += m_shapes[i]->vertexBufferSize();
         totalElementBufferSize += m_shapes[i]->indexBufferSize();
     }
     glGenBuffers(1, &m_vertexBufferID);
     glBindBuffer(GL_ARRAY_BUFFER, m_vertexBufferID);
     glBufferData(GL_ARRAY_BUFFER, totalVertexBufferSize, 0, GL_DYNAMIC_DRAW);
     GLsizeiptr currentVertexOffset = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         m_vertexOffsets[i] = currentVertexOffset;
         glBufferSubData(GL_ARRAY_BUFFER, currentVertexOffset, m_shapes[i]->vertexBufferSize(), m_shapes[i]->vertices);
         currentVertexOffset += m_shapes[i]->vertexBufferSize();
     }
     glGenBuffers(1, &m_elementBufferID);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_elementBufferID);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, totalElementBufferSize, 0, GL_STATIC_DRAW);
     GLsizeiptr currentElementOffset = 0;
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         m_elementOffsets[i] = currentElementOffset;
         glBufferSubData(GL_ELEMENT_ARRAY_BUFFER, currentElementOffset, m_shapes[i]->indexBufferSize(), m_shapes[i]->indices);
         currentElementOffset += m_shapes[i]->indexBufferSize();
     }
     for (size_t i = 0; i < m_shapes.size(); i++)
     {
         //glDeleteVertexArrays(1, &m_vertexArrayObjectIDs[i]);
         glGenVertexArrays(1, &m_vertexArrayObjectIDs[i]);
         glBindVertexArray(m_vertexArrayObjectIDs[i]);
         glEnableVertexAttribArray(0);
         glEnableVertexAttribArray(1);
         glEnableVertexAttribArray(2);
         glBindBuffer(GL_ARRAY_BUFFER, m_vertexBufferID);
         glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i]));
         glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i] + sizeof(float)* 3));
         glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, VERTEX_BYTE_SIZE, (void*)(m_vertexOffsets[i] + sizeof(float)* 6));
         glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_elementBufferID);
     }
     //glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_elementBufferID);
 }
setBoundingSphereRadius()
void myRenderer::setBoundingSphereRadius (float _radius) inline
Definition at line 209 of file myRenderer.h.
References boundingSphereRadius.
 {boundingSphereRadius = _radius;}
setDefaultValues()
void myRenderer::setDefaultValues ()
setDefaultValues - set custom renderer parameters
Definition at line 238 of file myRenderer.cpp.
References initializeInteractor(), m_far, m_fov, m_height, m_near, m_width, modelToWorldMatrix, and sceneCentralPoint.
Referenced by myGLWindow::setShape().
 {
     //currentDrawFlag = e_draw_faces;
     sceneCentralPoint = glm::vec3(0.0f, 0.0f, 0.0f);
     m_width = 1000;
     m_height = 800;
     m_fov = 45.0f;
     m_near = 0.01f;
     m_far = 1000.0f;
     modelToWorldMatrix = glm::translate(glm::vec3(0.0f, 0.0f, 0.0f));
     initializeInteractor();
 }
setFar()
void myRenderer::setFar (GLfloat _far) inline
Definition at line 206 of file myRenderer.h.
References m_far.
 {m_far = _far;}
setFOV()
void myRenderer::setFOV (GLfloat _fov) inline
Definition at line 204 of file myRenderer.h.
References m_fov.
 {m_fov = _fov;}
setHeight()
void myRenderer::setHeight (GLuint _height) inline
Definition at line 203 of file myRenderer.h.
References m_height.
Referenced by myGLWindow::paintGL().
 {m_height = _height;}
setModelToWorldMatrix()
void myRenderer::setModelToWorldMatrix (glm::mat4 & _modelToWorldMatrix) inline
Definition at line 207 of file myRenderer.h.
References modelToWorldMatrix.
 {modelToWorldMatrix = _modelToWorldMatrix;}
setNear()
void myRenderer::setNear (GLfloat _near) inline
Definition at line 205 of file myRenderer.h.
References m_near.
 {m_near = _near;}
setSceneCentralPoint()
void myRenderer::setSceneCentralPoint (glm::vec3 & _point) inline
Definition at line 208 of file myRenderer.h.
References sceneCentralPoint.
 {sceneCentralPoint = _point;}
setShapeDrawMode()
void myRenderer::setShapeDrawMode (size_t _shape_index, myDrawFlags _mode)
setShapeDrawMode - set rendering mode for a specific shape
Parameters
_shape_index index of the target shape
_mode rendering mode for the target shape
Definition at line 98 of file myRenderer.cpp.
References m_draw_modes.
Referenced by myGLWindow::setVisualizationMode().
 {
     m_draw_modes[_shape_index] = _mode;
 }
setWidth()
void myRenderer::setWidth (GLuint _width) inline
setters
Definition at line 202 of file myRenderer.h.
References m_width.
Referenced by myGLWindow::paintGL().
 {m_width = _width;}
translateCamera()
void myRenderer::translateCamera (const glm::vec2 & newMousePosition)
translateCamera - translate all shapes (model to world matrix manipulation) regarding a mouse movement interaction
Parameters
newMousePosition current mouse position
Definition at line 433 of file myRenderer.cpp.
References camera, myCamera::getMovementSpeed(), myCamera::getPosition(), myCamera::getStrafeDirection(), myCamera::getUP(), oldMousePosition, and myCamera::setPosition().
Referenced by myGLWindow::event().
 {
     glm::vec2 mouseDelta = newMousePosition - oldMousePosition;
     if (glm::length(mouseDelta) > 20.0f)
     {
         oldMousePosition = newMousePosition;
         return;
     }
     float TRANSLATION_SPEED = camera.getMovementSpeed();
     float valx = mouseDelta.x * TRANSLATION_SPEED;
     float valy = mouseDelta.y * TRANSLATION_SPEED;
     camera.setPosition(camera.getPosition()-camera.getUP()*valy+camera.getStrafeDirection()*valx);
     oldMousePosition = newMousePosition;
     return;
 }
updateVertexBuffer()
void myRenderer::updateVertexBuffer (size_t index)
updateVertexBuffer - update and send vertex data for a single shape
Parameters
index target shape index
Definition at line 370 of file myRenderer.cpp.
References m_shapes, m_vertexBufferID, and m_vertexOffsets.
Referenced by myGLWindow::updateMesh().
 {
     glBindBuffer(GL_ARRAY_BUFFER, m_vertexBufferID);
     glBufferSubData(GL_ARRAY_BUFFER, m_vertexOffsets[index], m_shapes[index]->vertexBufferSize(), m_shapes[index]->vertices);
 }
zoom()
void myRenderer::zoom (float delta)
zoom - translate camera position (forward/backward) regarding a step size
Parameters
delta - step size
Definition at line 452 of file myRenderer.cpp.
References camera, myCamera::moveBackward(), and myCamera::moveForward().
Referenced by myGLWindow::event().
 {
     if (delta >= 0.0f)
         camera.moveForward();
     else
         camera.moveBackward();
 }
Field Documentation
boundingSphereRadius
float myRenderer::boundingSphereRadius private
boundingSphereRadius - bounding sphere radius (regarding the central point)
Definition at line 268 of file myRenderer.h.
Referenced by computeBoundingSphereRadius(), getBoundingSphereRadius(), initializeInteractor(), and setBoundingSphereRadius().
camera
myCamera myRenderer::camera private
camera - main camera for renderer
Definition at line 239 of file myRenderer.h.
Referenced by draw(), getCamera(), getRayDirection(), initializeInteractor(), translateCamera(), and zoom().
light
glm::vec4 myRenderer::light private
light - main light "color"
Definition at line 243 of file myRenderer.h.
Referenced by draw(), and myRenderer().
lightPosition
glm::vec3 myRenderer::lightPosition private
lightPosition - main light position
Definition at line 247 of file myRenderer.h.
Referenced by draw(), and myRenderer().
m_draw_modes
vector<myDrawFlags> myRenderer::m_draw_modes private
m_draw_modes - vector containing all shape rendering modes
Definition at line 308 of file myRenderer.h.
Referenced by addShape(), clearAndDeleteShapes(), clearShapes(), draw(), removeShape(), and setShapeDrawMode().
m_elementBufferID
GLuint myRenderer::m_elementBufferID private
m_elementBufferID - main element buffer ID
Definition at line 284 of file myRenderer.h.
Referenced by resendDataSingleBuffer(), sendDataSingleBuffer(), and ~myRenderer().
m_elementOffsets
vector<GLsizeiptr> myRenderer::m_elementOffsets private
m_elementOffsets - vector containing all shape indices offsets
Definition at line 300 of file myRenderer.h.
Referenced by addShape(), clearAndDeleteShapes(), clearShapes(), draw(), getIndexOffsetAt(), removeShape(), resendDataSingleBuffer(), and sendDataSingleBuffer().
m_far
GLfloat myRenderer::m_far private
m_far - far plane distance
Definition at line 235 of file myRenderer.h.
Referenced by draw(), getFar(), getRayDirection(), myRenderer(), setDefaultValues(), and setFar().
m_fov
GLfloat myRenderer::m_fov private
m_fov - field of view (FOV)
Definition at line 227 of file myRenderer.h.
Referenced by draw(), getFOV(), getRayDirection(), myRenderer(), setDefaultValues(), and setFOV().
m_height
GLuint myRenderer::m_height private
m_height - window height
Definition at line 223 of file myRenderer.h.
Referenced by draw(), getHeight(), getRayDirection(), myRenderer(), setDefaultValues(), and setHeight().
m_near
GLfloat myRenderer::m_near private
m_near - near plane distance
Definition at line 231 of file myRenderer.h.
Referenced by draw(), getNear(), getRayDirection(), myRenderer(), setDefaultValues(), and setNear().
m_programID
GLuint myRenderer::m_programID private
Data.
m_programID - main program ID
Definition at line 276 of file myRenderer.h.
Referenced by clearAndDeleteShaders(), createProgram(), draw(), getProgramID(), installShaders(), and ~myRenderer().
m_shaders
vector<myShader*> myRenderer::m_shaders private
m_shaders - vector containing all shaders
Definition at line 288 of file myRenderer.h.
Referenced by addShader(), clearAndDeleteShaders(), clearShaders(), and installShaders().
m_shapes
vector<ShapeData*> myRenderer::m_shapes private
m_shapes - vector containing all shapes
Definition at line 292 of file myRenderer.h.
Referenced by addShape(), clearAndDeleteShapes(), clearShapes(), computeBoundingSphereRadius(), computeCentralPoint(), draw(), getNumberOfShapes(), removeShape(), resendDataSingleBuffer(), sendDataSingleBuffer(), and updateVertexBuffer().
m_vertexArrayObjectIDs
vector<GLuint> myRenderer::m_vertexArrayObjectIDs private
m_vertexArrayObjectIDs - vector containing all vertex array objects IDs
Definition at line 304 of file myRenderer.h.
Referenced by addShape(), clearAndDeleteShapes(), clearShapes(), draw(), getVertexArrayObjectIDAt(), removeShape(), resendDataSingleBuffer(), and sendDataSingleBuffer().
m_vertexBufferID
GLuint myRenderer::m_vertexBufferID private
m_vertexBufferID - main vertex buffer ID
Definition at line 280 of file myRenderer.h.
Referenced by resendDataSingleBuffer(), sendDataSingleBuffer(), updateVertexBuffer(), and ~myRenderer().
m_vertexOffsets
vector<GLsizeiptr> myRenderer::m_vertexOffsets private
m_vertexOffsets - vector containing all shape vertices offsets
Definition at line 296 of file myRenderer.h.
Referenced by addShape(), clearAndDeleteShapes(), clearShapes(), removeShape(), resendDataSingleBuffer(), sendDataSingleBuffer(), and updateVertexBuffer().
m_width
GLuint myRenderer::m_width private
Rendering.
m_width - window width
Definition at line 219 of file myRenderer.h.
Referenced by draw(), getRayDirection(), getWidth(), myRenderer(), setDefaultValues(), and setWidth().
modelToWorldMatrix
glm::mat4 myRenderer::modelToWorldMatrix private
Interaction.
modelToWorldMatrix - 4x4 model to world matrix (for all shapes)
Definition at line 255 of file myRenderer.h.
Referenced by draw(), getModelToWorldMatrix(), myRenderer(), rotateObjects(), setDefaultValues(), and setModelToWorldMatrix().
oldMousePosition
glm::vec2 myRenderer::oldMousePosition private
oldMousePosition - old mouse position for mouse move interactions
Definition at line 259 of file myRenderer.h.
Referenced by rotateObjects(), and translateCamera().
sceneCentralPoint
glm::vec3 myRenderer::sceneCentralPoint private
sceneCentralPoint - scene central point
Definition at line 264 of file myRenderer.h.
Referenced by computeBoundingSphereRadius(), computeCentralPoint(), getSceneCentralPoint(), initializeInteractor(), myRenderer(), rotateObjects(), setDefaultValues(), and setSceneCentralPoint().
The documentation for this class was generated from the following files:
visualization/myRenderer.h
visualization/myRenderer.cpp