Mesh Smoothing Tool: myMainWindow Class Reference
myMainWindow Class Reference
The myMainWindow class - Main Window for mesh smoothing application.
#include <myMainWindow.h>
Public Member Functions
myMainWindow ()
myMainWindow - default constructor: dynamic building of all the interface
~myMainWindow ()
~myMainWindow - destructor
Protected Member Functions
void keyPressEvent (QKeyEvent *e)
keyPressEvent - Qt key press event
void keyReleaseEvent (QKeyEvent *e)
keyReleaseEvent - Qt key release event
bool eventFilter (QObject *object, QEvent *event)
eventFilter - Qt event filter
Private Member Functions
void createActions ()
createActions - create menu actions and connect all signals and slots
void createMenus ()
createMenus - create menus
void updateWidgetValues ()
updateWidgetValues - set default slider widget values (min, max and current)
void setSmoothingThread ()
setSmoothingThread - set thread for global smoothing
void loadMesh ()
loadMesh - load input mesh from a file supported by OpenMesh library
void saveMesh ()
saveMesh - save output mesh to a file supported by OpenMesh library
void exit ()
exit - close the application
void flatMode ()
flatMode - set triangle rendering
void wireframeMode ()
wireframeMode - set wireframe rendering
void pointsMode ()
pointsMode - set point rendering
void setShaders ()
setShaders - set shaders profile (customizable)
void setGlobalSmoothingAlgorithm ()
setGlobalSmoothingAlgorithm - set global smoothing algorithm
void setFocalizedSmoothingAlgorithm ()
setFocalizedSmoothingAlgorithm - set focalized smoothing algorithm
void about ()
about - show about window
void userGuide ()
userGuide - show user guide
void enableSmoothingType ()
enableSmoothingType - enable widgets for current smoothing type
void runGlobalSmoothing ()
runGlobalSmoothing - run global smoothing algorithm
void stopGlobalSmoothing ()
stopGlobalSmoothing - stop global smoothing
void continueGlobalSmoothing ()
continueGlobalSmoothing - continue global smoothing
void updateGlobalSmoothing ()
updateGlobalSmoothing - global smoothing management (step by step)
void setGlobalSmoothingStatus (globalSmoothingStatus current_status)
setGlobalSmoothingStatus - set current global smoothing status
void reinitializeOutput ()
reinitializeOutput - reinitialize output mesh (regarding input mesh)
void setOutputAsInput ()
setOutputAsInput - set output mesh as new input mesh
void getSelection (vector< size_t > &selected_vertices_ids)
getSelection - get selected vertices for the current mouse position in the output mesh visualizer
void updateSelection ()
updateSelection - update selection in data manager and visualization
void removeSelection ()
removeSelection - remove selection from data manager and visualization
void selectAndSmooth ()
selectAndSmooth - select and perform focalized smoothing regarding control widget values
Private Attributes
myGLWindow * input_mesh_visualizer_ptr
myGLWindow * output_mesh_visualizer_ptr
QWidget * widget
QHBoxLayout * layout
QScrollArea * control_scroll_area
QVBoxLayout * control_layout
QGroupBox * group_box_smoothing_type
QGroupBox * group_box_global_smoothing
QGroupBox * group_box_focalized_smoothing
QGroupBox * group_box_data_manipulation
QHBoxLayout * layout_smoothing_type
Auxiliar Layouts.
QVBoxLayout * layout_global_smoothing
QHBoxLayout * layout_global_smoothing_buttons
QVBoxLayout * layout_focalized_smoothing
QHBoxLayout * layout_data_manipulation
QRadioButton * radio_button_smoothing_type_g
QRadioButton * radio_button_smoothing_type_f
QPushButton * push_button_global_smoothing_run
QPushButton * push_button_global_smoothing_stop
QPushButton * push_button_global_smoothing_continue
QPushButton * push_button_reinitialize_data
QPushButton * push_button_update_input_data
QSlider * slider_gs_smoothness
QSlider * slider_gs_radius_ratio
QSlider * slider_gs_detail_preservation
QSlider * slider_fs_smoothness
QSlider * slider_fs_radius
QProgressBar * progress_bar
QMenu * fileMenu
QMenu * viewMenu
QMenu * settingsMenu
QMenu * helpMenu
QActionGroup * alignmentGroup
Menu Actions.
QAction * loadAct
QAction * saveAct
QAction * exitAct
QAction * flatModeAct
QAction * wireframeModeAct
QAction * pointsModeAct
QAction * setShadersAct
QAction * setGlobalSmoothingAlgorithmAct
QAction * setFocalizedSmoothingAlgorithmAct
QAction * aboutAct
QAction * userGuideAct
myDataManager data
QThread smoothingThread
GlobalSmoothingTask * smoothingTask
globalSmoothingAlgorithm currentGlobalSmoothingAlgorithm
focalizedSmoothingAlgorithm currentFocalizedSmoothingAlgorithm
bool selectionMode
bool runningStatus
bool globalSmoothingStopped
Detailed Description
The myMainWindow class - Main Window for mesh smoothing application.
Definition at line 69 of file myMainWindow.h.
Constructor & Destructor Documentation
myMainWindow()
myMainWindow::myMainWindow ()
myMainWindow - default constructor: dynamic building of all the interface
Definition at line 3 of file myMainWindow.cpp.
References control_layout, control_scroll_area, createActions(), createMenus(), currentFocalizedSmoothingAlgorithm, currentGlobalSmoothingAlgorithm, enableSmoothingType(), fs_algorithm_uniform_laplacian, globalSmoothingStopped, group_box_data_manipulation, group_box_focalized_smoothing, group_box_global_smoothing, group_box_smoothing_type, gs_algorithm_bilateral_normal, gs_status_init, input_mesh_visualizer_ptr, layout, layout_data_manipulation, layout_focalized_smoothing, layout_global_smoothing, layout_global_smoothing_buttons, layout_smoothing_type, output_mesh_visualizer_ptr, progress_bar, push_button_global_smoothing_continue, push_button_global_smoothing_run, push_button_global_smoothing_stop, push_button_reinitialize_data, push_button_update_input_data, radio_button_smoothing_type_f, radio_button_smoothing_type_g, runningStatus, selectionMode, setGlobalSmoothingStatus(), setSmoothingThread(), slider_fs_radius, slider_fs_smoothness, slider_gs_detail_preservation, slider_gs_radius_ratio, slider_gs_smoothness, and widget.
 {
     const int control_block_max_width = 250;
     input_mesh_visualizer_ptr = new myGLWindow(this);
     output_mesh_visualizer_ptr = new myGLWindow(this);
     radio_button_smoothing_type_g = new QRadioButton("Global");
     radio_button_smoothing_type_f = new QRadioButton("Focalized");
     radio_button_smoothing_type_g->setChecked(true);
     push_button_global_smoothing_run = new QPushButton("&Run", this);
     push_button_global_smoothing_stop = new QPushButton("&Stop", this);
     push_button_global_smoothing_continue = new QPushButton("&Continue", this);
     push_button_reinitialize_data = new QPushButton("&Restart", this);
     push_button_update_input_data = new QPushButton("&Update", this);
     slider_gs_smoothness = new QSlider(Qt::Horizontal, this);
     slider_gs_radius_ratio = new QSlider(Qt::Horizontal, this);
     slider_gs_detail_preservation = new QSlider(Qt::Horizontal, this);
     progress_bar = new QProgressBar(this);
     slider_fs_smoothness = new QSlider(Qt::Horizontal, this);
     slider_fs_radius = new QSlider(Qt::Horizontal, this);
     layout_smoothing_type = new QHBoxLayout;
     layout_smoothing_type->addWidget(radio_button_smoothing_type_g);
     layout_smoothing_type->addWidget(radio_button_smoothing_type_f);
     layout_global_smoothing_buttons = new QHBoxLayout;
     layout_global_smoothing_buttons->addWidget(push_button_global_smoothing_run);
     layout_global_smoothing_buttons->addWidget(push_button_global_smoothing_stop);
     layout_global_smoothing_buttons->addWidget(push_button_global_smoothing_continue);
     layout_global_smoothing = new QVBoxLayout;
     layout_global_smoothing->addWidget(new QLabel("Smoothness", this));
     layout_global_smoothing->addWidget(slider_gs_smoothness);
     layout_global_smoothing->addWidget(new QLabel("Influence radius ratio",this));
     layout_global_smoothing->addWidget(slider_gs_radius_ratio);
     layout_global_smoothing->addWidget(new QLabel("Detail preservation", this));
     layout_global_smoothing->addWidget(slider_gs_detail_preservation);
     layout_global_smoothing->addWidget(progress_bar);
     layout_global_smoothing->addLayout(layout_global_smoothing_buttons);
     layout_focalized_smoothing = new QVBoxLayout;
     layout_focalized_smoothing->addWidget(new QLabel("Smoothness", this));
     layout_focalized_smoothing->addWidget(slider_fs_smoothness);
     layout_focalized_smoothing->addWidget(new QLabel("Radius", this));
     layout_focalized_smoothing->addWidget(slider_fs_radius);
     layout_data_manipulation = new QHBoxLayout;
     layout_data_manipulation->addWidget(push_button_reinitialize_data);
     layout_data_manipulation->addWidget(push_button_update_input_data);
     group_box_smoothing_type = new QGroupBox(tr("Smoothing type"));
     group_box_smoothing_type->setMaximumWidth(control_block_max_width);
     group_box_smoothing_type->setLayout(layout_smoothing_type);
     group_box_global_smoothing = new QGroupBox(tr("Global smoothing"));
     group_box_global_smoothing->setMaximumWidth(control_block_max_width);
     group_box_global_smoothing->setLayout(layout_global_smoothing);
     group_box_focalized_smoothing = new QGroupBox(tr("Focalized smoothing"));
     group_box_focalized_smoothing->setMaximumWidth(control_block_max_width);
     group_box_focalized_smoothing->setLayout(layout_focalized_smoothing);
     group_box_data_manipulation = new QGroupBox(tr("Data manipulation"));
     group_box_data_manipulation->setMaximumWidth(control_block_max_width);
     group_box_data_manipulation->setLayout(layout_data_manipulation);
     control_layout = new QVBoxLayout;
     control_layout->addWidget(group_box_smoothing_type);
     control_layout->addWidget(group_box_global_smoothing);
     control_layout->addWidget(group_box_focalized_smoothing);
     control_layout->addWidget(group_box_data_manipulation);
     control_layout->addStretch();
     QWidget * t_widget = new QWidget(this);
     t_widget->setLayout(control_layout);
     control_scroll_area = new QScrollArea(this);
     control_scroll_area->setWidget(t_widget);
     control_scroll_area->setMaximumWidth(control_block_max_width+40);
     layout = new QHBoxLayout;
     layout->addWidget(input_mesh_visualizer_ptr);
     layout->addWidget(output_mesh_visualizer_ptr);
     layout->addWidget(control_scroll_area);
     widget = new QWidget;
     widget->setLayout(layout);
     setCentralWidget(widget);
     createActions();
     createMenus();
     setSmoothingThread();
     QString message = tr("A context menu is available by right-clicking");
     statusBar()->showMessage(message);
     setWindowTitle(tr("Mesh Smoothing Tool"));
     setMinimumSize(480, 320);
     resize(1200, 600);
     enableSmoothingType();
     //setMouseTracking(true);
     output_mesh_visualizer_ptr->installEventFilter(this);
     selectionMode = 0;
     runningStatus = 0;
     globalSmoothingStopped = 0;
     setGlobalSmoothingStatus(gs_status_init);
     currentGlobalSmoothingAlgorithm = gs_algorithm_bilateral_normal;
     currentFocalizedSmoothingAlgorithm = fs_algorithm_uniform_laplacian;
 }
~myMainWindow()
myMainWindow::~myMainWindow ()
~myMainWindow - destructor
Definition at line 126 of file myMainWindow.cpp.
References smoothingThread.
 {
     smoothingThread.quit();
     smoothingThread.wait();
 }
Member Function Documentation
about()
void myMainWindow::about () private
about - show about window
Definition at line 409 of file myMainWindow.cpp.
Referenced by createActions().
 {
     QMessageBox msgBox;
     msgBox.setWindowTitle("About");
     msgBox.setText("Mesh Smoothing Tool v1.0");
     msgBox.setInformativeText("A mesh processing tool for surface smoothing");
     int ret = msgBox.exec();
 }
continueGlobalSmoothing()
void myMainWindow::continueGlobalSmoothing () private
continueGlobalSmoothing - continue global smoothing
Definition at line 504 of file myMainWindow.cpp.
References gs_status_continuing, setGlobalSmoothingStatus(), and smoothingThread.
Referenced by createActions().
 {
     smoothingThread.start();
     setGlobalSmoothingStatus(gs_status_continuing);
 }
createActions()
void myMainWindow::createActions () private
createActions - create menu actions and connect all signals and slots
Definition at line 132 of file myMainWindow.cpp.
References about(), aboutAct, continueGlobalSmoothing(), enableSmoothingType(), exit(), exitAct, flatMode(), flatModeAct, loadAct, loadMesh(), pointsMode(), pointsModeAct, push_button_global_smoothing_continue, push_button_global_smoothing_run, push_button_global_smoothing_stop, push_button_reinitialize_data, push_button_update_input_data, radio_button_smoothing_type_f, radio_button_smoothing_type_g, reinitializeOutput(), runGlobalSmoothing(), saveAct, saveMesh(), setFocalizedSmoothingAlgorithm(), setFocalizedSmoothingAlgorithmAct, setGlobalSmoothingAlgorithm(), setGlobalSmoothingAlgorithmAct, setOutputAsInput(), setShaders(), setShadersAct, stopGlobalSmoothing(), userGuide(), userGuideAct, wireframeMode(), and wireframeModeAct.
Referenced by myMainWindow().
 {
     connect(push_button_global_smoothing_run, &QPushButton::released, this, &myMainWindow::runGlobalSmoothing);
     connect(push_button_global_smoothing_stop, &QPushButton::released, this, &myMainWindow::stopGlobalSmoothing);
     connect(push_button_global_smoothing_continue, &QPushButton::released, this, &myMainWindow::continueGlobalSmoothing);
     connect(radio_button_smoothing_type_g, &QRadioButton::released, this, &myMainWindow::enableSmoothingType);
     connect(radio_button_smoothing_type_f, &QRadioButton::released, this, &myMainWindow::enableSmoothingType);
     connect(push_button_reinitialize_data, &QPushButton::released, this, &myMainWindow::reinitializeOutput);
     connect(push_button_update_input_data, &QPushButton::released, this, &myMainWindow::setOutputAsInput);
     loadAct = new QAction(tr("&Load"), this);
     loadAct->setShortcuts(QKeySequence::Open);
     loadAct->setStatusTip(tr("Load input mesh"));
     connect(loadAct, &QAction::triggered, this, &myMainWindow::loadMesh);
     saveAct = new QAction(tr("&Save"), this);
     saveAct->setShortcuts(QKeySequence::Save);
     saveAct->setStatusTip(tr("Save output mesh"));
     connect(saveAct, &QAction::triggered, this, &myMainWindow::saveMesh);
     exitAct = new QAction(tr("&Exit"), this);
     exitAct->setShortcuts(QKeySequence::Close);
     exitAct->setStatusTip(tr("Exit program"));
     connect(exitAct, &QAction::triggered, this, &myMainWindow::exit);
     flatModeAct = new QAction(tr("&Flat"), this);
     flatModeAct->setStatusTip(tr("Flat rendering"));
     connect(flatModeAct, &QAction::triggered, this, &myMainWindow::flatMode);
     wireframeModeAct = new QAction(tr("&Wireframe"), this);
     wireframeModeAct->setStatusTip(tr("Wireframe rendering"));
     connect(wireframeModeAct, &QAction::triggered, this, &myMainWindow::wireframeMode);
     pointsModeAct = new QAction(tr("&Points"), this);
     pointsModeAct->setStatusTip(tr("Point rendering"));
     connect(pointsModeAct, &QAction::triggered, this, &myMainWindow::pointsMode);
     setShadersAct = new QAction(tr("&Set shaders"), this);
     setShadersAct->setStatusTip(tr("Set shaders"));
     connect(setShadersAct, &QAction::triggered, this, &myMainWindow::setShaders);
     setGlobalSmoothingAlgorithmAct = new QAction(tr("&Set global smoothing algorithm"), this);
     setGlobalSmoothingAlgorithmAct->setStatusTip(tr("Set global smoothing algorithm"));
     connect(setGlobalSmoothingAlgorithmAct, &QAction::triggered, this, &myMainWindow::setGlobalSmoothingAlgorithm);
     setFocalizedSmoothingAlgorithmAct = new QAction(tr("&Set focalized smoothing algorithm"), this);
     setFocalizedSmoothingAlgorithmAct->setStatusTip(tr("Set focalized smoothing algorithm"));
     connect(setFocalizedSmoothingAlgorithmAct, &QAction::triggered, this, &myMainWindow::setFocalizedSmoothingAlgorithm);
     aboutAct = new QAction(tr("&About"), this);
     aboutAct->setStatusTip(tr("About"));
     connect(aboutAct, &QAction::triggered, this, &myMainWindow::about);
     userGuideAct = new QAction(tr("&User Guide"), this);
     userGuideAct->setStatusTip(tr("User Guide"));
     connect(userGuideAct, &QAction::triggered, this, &myMainWindow::userGuide);
 }
createMenus()
void myMainWindow::createMenus () private
createMenus - create menus
Definition at line 190 of file myMainWindow.cpp.
References aboutAct, exitAct, fileMenu, flatModeAct, helpMenu, loadAct, pointsModeAct, saveAct, setFocalizedSmoothingAlgorithmAct, setGlobalSmoothingAlgorithmAct, setShadersAct, settingsMenu, userGuideAct, viewMenu, and wireframeModeAct.
Referenced by myMainWindow().
 {
     fileMenu = menuBar()->addMenu(tr("&File"));
     fileMenu->addAction(loadAct);
     fileMenu->addAction(saveAct);
     fileMenu->addAction(exitAct);
     viewMenu = menuBar()->addMenu(tr("&View"));
     viewMenu->addAction(flatModeAct);
     viewMenu->addAction(wireframeModeAct);
     viewMenu->addAction(pointsModeAct);
     settingsMenu = menuBar()->addMenu(tr("&Settings"));
     settingsMenu->addAction(setShadersAct);
     settingsMenu->addAction(setGlobalSmoothingAlgorithmAct);
     settingsMenu->addAction(setFocalizedSmoothingAlgorithmAct);
     helpMenu = menuBar()->addMenu(tr("&Help"));
     helpMenu->addAction(aboutAct);
     helpMenu->addAction(userGuideAct);
 }
enableSmoothingType()
void myMainWindow::enableSmoothingType () private
enableSmoothingType - enable widgets for current smoothing type
Definition at line 560 of file myMainWindow.cpp.
References group_box_focalized_smoothing, group_box_global_smoothing, and radio_button_smoothing_type_g.
Referenced by createActions(), and myMainWindow().
 {
     if (radio_button_smoothing_type_g->isChecked())
     {
         group_box_global_smoothing->setEnabled(true);
         group_box_focalized_smoothing->setEnabled(false);
     }
     else
     {
         group_box_global_smoothing->setEnabled(false);
         group_box_focalized_smoothing->setEnabled(true);
     }
 }
eventFilter()
bool myMainWindow::eventFilter (QObject * object, QEvent * event) protected
eventFilter - Qt event filter
Parameters
object current object
event current event
Returns
success
Definition at line 621 of file myMainWindow.cpp.
References output_mesh_visualizer_ptr, removeSelection(), selectAndSmooth(), selectionMode, and updateSelection().
 {
     if (object == output_mesh_visualizer_ptr)
     {
         if (event->type() == QEvent::MouseMove)
         {
             QMouseEvent * e = static_cast<QMouseEvent *>(event);
             if (e->modifiers() & Qt::ShiftModifier)
             {
                 selectionMode = 1;
                 updateSelection();
                 return true;
             }
             else
             {
                 selectionMode = 0;
                 removeSelection();
                 return false;
             }
         }
         if (event->type() == QEvent::MouseButtonRelease)
         {
             QMouseEvent * e = static_cast<QMouseEvent *>(event);
             if (e->modifiers() & Qt::ShiftModifier)
             {
                 if (e->button() == Qt::LeftButton)
                 {
                     cout << "Focalized Smoothing ... ";
                     selectionMode = 1;
                     selectAndSmooth();
                     return true;
                 }
             }
         }
     }
     return QWidget::eventFilter(object, event);
 }
exit()
void myMainWindow::exit () private
exit - close the application
Definition at line 267 of file myMainWindow.cpp.
Referenced by createActions().
 {
     close();
 }
flatMode()
void myMainWindow::flatMode () private
flatMode - set triangle rendering
Definition at line 272 of file myMainWindow.cpp.
References e_draw_faces, input_mesh_visualizer_ptr, output_mesh_visualizer_ptr, and myGLWindow::setVisualizationMode().
Referenced by createActions().
 {
     input_mesh_visualizer_ptr->setVisualizationMode(e_draw_faces);
     output_mesh_visualizer_ptr->setVisualizationMode(e_draw_faces);
 }
getSelection()
void myMainWindow::getSelection (vector< size_t > & selected_vertices_ids) private
getSelection - get selected vertices for the current mouse position in the output mesh visualizer
Parameters
selected_vertices_ids - output vector of selected vertices IDs
Definition at line 659 of file myMainWindow.cpp.
References data, myGLWindow::getCamera(), myGLWindow::getCurrentMousePosition(), myGLWindow::getModelToWorldMatrix(), myCamera::getPosition(), myGLWindow::getRayDirection(), getVertexNeighbors(), myDataManager::output_mesh, output_mesh_visualizer_ptr, and slider_fs_radius.
Referenced by selectAndSmooth(), and updateSelection().
 {
     selected_vertices_ids.clear();
     int k = slider_fs_radius->value();
     glm::vec2 mousePos = output_mesh_visualizer_ptr->getCurrentMousePosition();
     glm::vec3 dir = output_mesh_visualizer_ptr->getRayDirection(mousePos);
     //cout << dir.x << " " << dir.y << " " << dir.z << endl;
     vector<TriMesh::VertexHandle> selected_vertices;
     glm::mat4 trMatrix = output_mesh_visualizer_ptr->getModelToWorldMatrix();
     //compute neighborhood
     float min_dist = 999999.0f;
     TriMesh::VertexHandle nearest_vertex_handle;
     for (TriMesh::FaceIter f_it = data.output_mesh.faces_begin(); f_it != data.output_mesh.faces_end(); f_it++)
     {
         glm::vec3 a, b, c;
         TriMesh::VertexHandle a_vh, b_vh, c_vh;
         TriMesh::FaceVertexIter fv_it = data.output_mesh.fv_iter(*f_it);
         a = glm::vec3(data.output_mesh.point(*fv_it)[0], data.output_mesh.point(*fv_it)[1], data.output_mesh.point(*fv_it)[2]);
         a = glm::vec3(trMatrix*glm::vec4(a, 1.0));
         a_vh = *fv_it;
         fv_it++;
         b = glm::vec3(data.output_mesh.point(*fv_it)[0], data.output_mesh.point(*fv_it)[1], data.output_mesh.point(*fv_it)[2]);
         b = glm::vec3(trMatrix*glm::vec4(b, 1.0));
         b_vh = *fv_it;
         fv_it++;
         c = glm::vec3(data.output_mesh.point(*fv_it)[0], data.output_mesh.point(*fv_it)[1], data.output_mesh.point(*fv_it)[2]);
         c = glm::vec3(trMatrix*glm::vec4(c, 1.0));
         c_vh = *fv_it;
         glm::vec3 ab = b - a;
         glm::vec3 ac = c - a;
         glm::vec3 normal = glm::cross(ab, ac);
         glm::vec3 o = output_mesh_visualizer_ptr->getCamera()->getPosition();
         float val = glm::dot(dir, normal);
         if (val == 0.0f) continue;
         float ti = glm::dot((a - o), normal) / val;
         glm::vec3 temp = dir*ti;
         glm::vec3 pi = o + temp;
         glm::vec3 v0 = b - a;
         glm::vec3 v1 = c - a;
         glm::vec3 v2 = pi - a;
         float d00 = glm::dot(v0, v0);
         float d01 = glm::dot(v0, v1);
         float d11 = glm::dot(v1, v1);
         float d20 = glm::dot(v2, v0);
         float d21 = glm::dot(v2, v1);
         double denom = glm::dot(d00, d11) - glm::dot(d01, d01);
         float v = (d11 * d20 - d01 * d21) / denom;
         float w = (d00 * d21 - d01 * d20) / denom;
         float u = 1.0 - v - w;
         bool liesOutside = v>1 || v<0 || w>1 || w<0 || u>1 || u<0;
         if (!liesOutside)
         {
             //cout << "intersect" << endl;
             if (ti < min_dist  && ti >= 0)
             {
                 if (u>v)
                 {
                     if (u > w)
                         nearest_vertex_handle = a_vh;
                     else
                         nearest_vertex_handle = c_vh;
                 }
                 else if (v > w)
                     nearest_vertex_handle = b_vh;
                 else
                     nearest_vertex_handle = c_vh;
                 min_dist = ti;
             }
         }
     }
     if (nearest_vertex_handle.is_valid())
     {
         getVertexNeighbors(data.output_mesh, nearest_vertex_handle, k, selected_vertices);
         selected_vertices.push_back(nearest_vertex_handle);
     }
     for (size_t i = 0; i < selected_vertices.size(); i++)
         selected_vertices_ids.push_back(selected_vertices[i].idx());
 }
keyPressEvent()
void myMainWindow::keyPressEvent (QKeyEvent * e) protected
keyPressEvent - Qt key press event
Parameters
e event
Definition at line 592 of file myMainWindow.cpp.
References output_mesh_visualizer_ptr, selectionMode, and updateSelection().
 {
     switch (e->key())
     {
     case Qt::Key::Key_Shift:
         if (selectionMode == 0)
         {
             selectionMode = 1;
             updateSelection();
             output_mesh_visualizer_ptr->repaint();
         }
         break;
     }
 }
keyReleaseEvent()
void myMainWindow::keyReleaseEvent (QKeyEvent * e) protected
keyReleaseEvent - Qt key release event
Parameters
e event
Definition at line 607 of file myMainWindow.cpp.
References removeSelection(), and selectionMode.
 {
     switch (e->key())
     {
     case Qt::Key::Key_Shift:
         if (selectionMode == 1)
         {
             selectionMode = 0;
             removeSelection();
         }
         break;
     }
 }
loadMesh()
void myMainWindow::loadMesh () private
loadMesh - load input mesh from a file supported by OpenMesh library
Definition at line 241 of file myMainWindow.cpp.
References data, myDataManager::input_mesh_shape, input_mesh_visualizer_ptr, myDataManager::loadInputMesh(), myDataManager::output_mesh_shape, output_mesh_visualizer_ptr, myGLWindow::setShape(), myDataManager::updateShapes(), and updateWidgetValues().
Referenced by createActions().
 {
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Load Mesh"), "",
         tr("mesh file format (*.obj *.off *.ply *.stl);;All Files (*)"));
     if (fileName == "") return;
     statusBar()->showMessage("Loading ... "+fileName);
     data.loadInputMesh(fileName.toStdString());
     data.updateShapes();
     input_mesh_visualizer_ptr->setShape(&data.input_mesh_shape);
     output_mesh_visualizer_ptr->setShape(&data.output_mesh_shape);
     statusBar()->showMessage("Done");
     updateWidgetValues();
 }
pointsMode()
void myMainWindow::pointsMode () private
pointsMode - set point rendering
Definition at line 284 of file myMainWindow.cpp.
References e_draw_points, input_mesh_visualizer_ptr, output_mesh_visualizer_ptr, and myGLWindow::setVisualizationMode().
Referenced by createActions().
 {
     input_mesh_visualizer_ptr->setVisualizationMode(e_draw_points);
     output_mesh_visualizer_ptr->setVisualizationMode(e_draw_points);
 }
reinitializeOutput()
void myMainWindow::reinitializeOutput () private
reinitializeOutput - reinitialize output mesh (regarding input mesh)
Definition at line 574 of file myMainWindow.cpp.
References data, input_mesh_visualizer_ptr, output_mesh_visualizer_ptr, myDataManager::reinitialize(), and myGLWindow::updateMesh().
Referenced by createActions().
 {
     data.reinitialize();
     input_mesh_visualizer_ptr->updateMesh();
     input_mesh_visualizer_ptr->repaint();
     output_mesh_visualizer_ptr->updateMesh();
     output_mesh_visualizer_ptr->repaint();
 }
removeSelection()
void myMainWindow::removeSelection () private
removeSelection - remove selection from data manager and visualization
Definition at line 778 of file myMainWindow.cpp.
References output_mesh_visualizer_ptr, and myGLWindow::removeSelection().
Referenced by eventFilter(), and keyReleaseEvent().
 {
     output_mesh_visualizer_ptr->removeSelection();
     output_mesh_visualizer_ptr->repaint();
 }
runGlobalSmoothing()
void myMainWindow::runGlobalSmoothing () private
runGlobalSmoothing - run global smoothing algorithm
Definition at line 510 of file myMainWindow.cpp.
References GlobalSmoothingTask::algorithm_flag, currentGlobalSmoothingAlgorithm, GlobalSmoothingTask::currentGlobalSmoothingIteration, GlobalSmoothingTask::finalGlobalSmoothingIteration, gs_status_started, GlobalSmoothingTask::iteration_step_size, GlobalSmoothingTask::n_vertex_iterations, setGlobalSmoothingStatus(), GlobalSmoothingTask::sigma_c_ratio, GlobalSmoothingTask::sigma_s, slider_gs_detail_preservation, slider_gs_radius_ratio, slider_gs_smoothness, smoothingTask, and smoothingThread.
Referenced by createActions().
 {
     const int default_iteration_step_size = 1;
     int smoothness_i = slider_gs_smoothness->value();
     float smoothness = static_cast<float>(slider_gs_smoothness->value());
     float radius_ratio = static_cast<float>(slider_gs_radius_ratio->value());
     float detail_preservation = static_cast<float>(slider_gs_detail_preservation->value());
     smoothingTask->n_vertex_iterations = static_cast<int>(smoothness/30.0f + 7.0f);
     smoothingTask->sigma_c_ratio = 0.5 + radius_ratio / 20.0f + smoothness/100.0f;
     smoothingTask->sigma_s = 0.8f-detail_preservation * 0.006f;
     cout << smoothingTask->sigma_s << endl;
     smoothingTask->iteration_step_size = default_iteration_step_size;
     smoothingTask->currentGlobalSmoothingIteration = 0;
     smoothingTask->finalGlobalSmoothingIteration = smoothness_i / default_iteration_step_size;
     smoothingTask->algorithm_flag = currentGlobalSmoothingAlgorithm;
     smoothingThread.start();
     setGlobalSmoothingStatus(gs_status_started);
 }
saveMesh()
void myMainWindow::saveMesh () private
saveMesh - save output mesh to a file supported by OpenMesh library
Definition at line 256 of file myMainWindow.cpp.
References data, and myDataManager::saveOutputMesh().
Referenced by createActions().
 {
     QString fileName = QFileDialog::getSaveFileName(this,
         tr("Save Mesh"), "",
         tr("mesh file format (*.obj *.off *.ply *.stl);;All Files (*)"));
     if (fileName == "") return;
     statusBar()->showMessage("Saving ... " + fileName);
     data.saveOutputMesh(fileName.toStdString());
     statusBar()->showMessage("Done");
 }
selectAndSmooth()
void myMainWindow::selectAndSmooth () private
selectAndSmooth - select and perform focalized smoothing regarding control widget values
Definition at line 758 of file myMainWindow.cpp.
References currentFocalizedSmoothingAlgorithm, data, fs_algorithm_hc_laplacian, fs_algorithm_uniform_laplacian, getSelection(), HCLaplacian(), myDataManager::output_mesh, output_mesh_visualizer_ptr, radio_button_smoothing_type_f, runningStatus, myDataManager::selection, myGLWindow::setSelection(), slider_fs_smoothness, uniformLaplacian(), myDataManager::updateOutputSelection(), and myDataManager::updateOutputShape().
Referenced by eventFilter().
 {
     if (!runningStatus && radio_button_smoothing_type_f->isChecked())
     {
         vector<size_t> selected_vertices_ids;
         getSelection(selected_vertices_ids);
         int num_its = slider_fs_smoothness->value();
         if (currentFocalizedSmoothingAlgorithm == fs_algorithm_uniform_laplacian)
             data.output_mesh = uniformLaplacian(data.output_mesh, num_its, 1.0f, selected_vertices_ids);
         else if ((currentFocalizedSmoothingAlgorithm == fs_algorithm_hc_laplacian))
             data.output_mesh = HCLaplacian(data.output_mesh, num_its, 0.5f,0.5f,selected_vertices_ids);
         else
             data.output_mesh = uniformLaplacian(data.output_mesh, num_its, 1.0f, selected_vertices_ids);
         data.updateOutputShape();
         data.updateOutputSelection(selected_vertices_ids);
         output_mesh_visualizer_ptr->setSelection(&data.selection);
         output_mesh_visualizer_ptr->repaint();
     }
 }
setFocalizedSmoothingAlgorithm()
void myMainWindow::setFocalizedSmoothingAlgorithm () private
setFocalizedSmoothingAlgorithm - set focalized smoothing algorithm
Definition at line 381 of file myMainWindow.cpp.
References currentFocalizedSmoothingAlgorithm, focalizedSmoothingAlgorithmLabels, fs_algorithm_hc_laplacian, and fs_algorithm_uniform_laplacian.
Referenced by createActions().
 {
     QInputDialog qDialog;
     QStringList items;
     items << QString(focalizedSmoothingAlgorithmLabels[fs_algorithm_uniform_laplacian].c_str());
     items << QString(focalizedSmoothingAlgorithmLabels[fs_algorithm_hc_laplacian].c_str());
     qDialog.setOptions(QInputDialog::UseListViewForComboBoxItems);
     qDialog.setComboBoxItems(items);
     qDialog.setWindowTitle("Focalized Smoothing Algorithm");
     qDialog.setLabelText("Choose focalized smoothing algorithm: ");
     qDialog.setTextValue(focalizedSmoothingAlgorithmLabels[currentFocalizedSmoothingAlgorithm].c_str());
     if (qDialog.exec())
     {
         if (qDialog.textValue().toStdString() == focalizedSmoothingAlgorithmLabels[fs_algorithm_uniform_laplacian])
             currentFocalizedSmoothingAlgorithm = fs_algorithm_uniform_laplacian;
         else if (qDialog.textValue().toStdString() == focalizedSmoothingAlgorithmLabels[fs_algorithm_hc_laplacian])
             currentFocalizedSmoothingAlgorithm = fs_algorithm_hc_laplacian;
         else
             currentFocalizedSmoothingAlgorithm = fs_algorithm_uniform_laplacian;
         QString message = tr(focalizedSmoothingAlgorithmLabels[currentFocalizedSmoothingAlgorithm].c_str());
         statusBar()->showMessage(message);
     }
 }
setGlobalSmoothingAlgorithm()
void myMainWindow::setGlobalSmoothingAlgorithm () private
setGlobalSmoothingAlgorithm - set global smoothing algorithm
Definition at line 353 of file myMainWindow.cpp.
References currentGlobalSmoothingAlgorithm, globalSmoothingAlgorithmLabels, gs_algorithm_bilateral_normal, and gs_algorithm_guided.
Referenced by createActions().
 {
     QInputDialog qDialog;
     QStringList items;
     items << QString(globalSmoothingAlgorithmLabels[gs_algorithm_bilateral_normal].c_str());
     items << QString(globalSmoothingAlgorithmLabels[gs_algorithm_guided].c_str());
     qDialog.setOptions(QInputDialog::UseListViewForComboBoxItems);
     qDialog.setComboBoxItems(items);
     qDialog.setWindowTitle("Global Smoothing Algorithm");
     qDialog.setLabelText("Choose global smoothing algorithm: ");
     qDialog.setTextValue(globalSmoothingAlgorithmLabels[currentGlobalSmoothingAlgorithm].c_str());
     if (qDialog.exec())
     {
         if (qDialog.textValue().toStdString() == globalSmoothingAlgorithmLabels[gs_algorithm_bilateral_normal])
             currentGlobalSmoothingAlgorithm = gs_algorithm_bilateral_normal;
         else if (qDialog.textValue().toStdString() == globalSmoothingAlgorithmLabels[gs_algorithm_guided])
             currentGlobalSmoothingAlgorithm = gs_algorithm_guided;
         else
             currentGlobalSmoothingAlgorithm = gs_algorithm_bilateral_normal;
         QString message = tr(globalSmoothingAlgorithmLabels[currentGlobalSmoothingAlgorithm].c_str());
         statusBar()->showMessage(message);
     }
 }
setGlobalSmoothingStatus()
void myMainWindow::setGlobalSmoothingStatus (globalSmoothingStatus current_status) private
setGlobalSmoothingStatus - set current global smoothing status
Parameters
current_status - global smoothing status
Definition at line 424 of file myMainWindow.cpp.
References globalSmoothingStopped, group_box_data_manipulation, group_box_smoothing_type, gs_status_continuing, gs_status_init, gs_status_started, gs_status_stopped, gs_status_stopping, progress_bar, push_button_global_smoothing_continue, push_button_global_smoothing_run, push_button_global_smoothing_stop, and runningStatus.
Referenced by continueGlobalSmoothing(), myMainWindow(), runGlobalSmoothing(), stopGlobalSmoothing(), and updateGlobalSmoothing().
 {
     if (current_status == gs_status_init)
     {
         push_button_global_smoothing_run->setEnabled(true);
         push_button_global_smoothing_stop->setEnabled(false);
         push_button_global_smoothing_continue->setEnabled(false);
         group_box_smoothing_type->setEnabled(true);
         group_box_data_manipulation->setEnabled(true);
         menuBar()->setEnabled(true);
         runningStatus = 0;
         globalSmoothingStopped = 0;
         QString message = tr("Ready ... ");
         statusBar()->showMessage(message);
     }
     else if (current_status == gs_status_started)
     {
         runningStatus = 1;
         globalSmoothingStopped = 0;
         progress_bar->setValue(0);
         push_button_global_smoothing_run->setEnabled(false);
         push_button_global_smoothing_stop->setEnabled(true);
         push_button_global_smoothing_continue->setEnabled(false);
         group_box_smoothing_type->setEnabled(false);
         group_box_data_manipulation->setEnabled(false);
         menuBar()->setEnabled(false);
         QString message = tr("Running ... ");
         statusBar()->showMessage(message);
     }
     else if (current_status == gs_status_stopping)
     {
         globalSmoothingStopped = 1;
         push_button_global_smoothing_stop->setEnabled(false);
         push_button_global_smoothing_continue->setEnabled(false);
         QString message = tr("Stopping ... ");
         statusBar()->showMessage(message);
     }
     else if (current_status == gs_status_stopped)
     {
         push_button_global_smoothing_run->setEnabled(true);
         group_box_smoothing_type->setEnabled(true);
         group_box_data_manipulation->setEnabled(true);
         menuBar()->setEnabled(true);
         push_button_global_smoothing_stop->setEnabled(false);
         push_button_global_smoothing_continue->setEnabled(true);
         runningStatus = 0;
         globalSmoothingStopped = 0;
         QString message = tr("Stopped ... ");
         statusBar()->showMessage(message);
     }
     else if (current_status == gs_status_continuing)
     {
         runningStatus = 1;
         globalSmoothingStopped = 0;
         push_button_global_smoothing_run->setEnabled(false);
         push_button_global_smoothing_stop->setEnabled(true);
         push_button_global_smoothing_continue->setEnabled(false);
         group_box_smoothing_type->setEnabled(false);
         group_box_data_manipulation->setEnabled(false);
         menuBar()->setEnabled(false);
         QString message = tr("Continuing ... ");
         statusBar()->showMessage(message);
     }
 }
setOutputAsInput()
void myMainWindow::setOutputAsInput () private
setOutputAsInput - set output mesh as new input mesh
Definition at line 583 of file myMainWindow.cpp.
References data, input_mesh_visualizer_ptr, output_mesh_visualizer_ptr, myDataManager::setOutputAsInput(), and myGLWindow::updateMesh().
Referenced by createActions().
 {
     data.setOutputAsInput();
     input_mesh_visualizer_ptr->updateMesh();
     input_mesh_visualizer_ptr->repaint();
     output_mesh_visualizer_ptr->updateMesh();
     output_mesh_visualizer_ptr->repaint();
 }
setShaders()
void myMainWindow::setShaders () private
setShaders - set shaders profile (customizable)
Definition at line 290 of file myMainWindow.cpp.
References myGLWindow::addShader(), myGLWindow::clearAndDeleteShaders(), input_mesh_visualizer_ptr, myGLWindow::installShaders(), and output_mesh_visualizer_ptr.
Referenced by createActions().
 {
     QInputDialog qDialog;
     QStringList items;
     items << QString("Flat");
     items << QString("Phong");
     items << QString("Normal Map");
     qDialog.setOptions(QInputDialog::UseListViewForComboBoxItems);
     qDialog.setComboBoxItems(items);
     qDialog.setWindowTitle("Shaders");
     qDialog.setLabelText("Choose shader options: ");
     if (!qDialog.exec()) return;
     if (qDialog.textValue().toStdString() == "Flat")
     {
         input_mesh_visualizer_ptr->clearAndDeleteShaders();
         input_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodeFlat.glsl");
         input_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodeFlat.glsl");
         input_mesh_visualizer_ptr->installShaders();
         output_mesh_visualizer_ptr->clearAndDeleteShaders();
         output_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodeFlat.glsl");
         output_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodeFlat.glsl");
         output_mesh_visualizer_ptr->installShaders();
         QString message = tr(qDialog.textValue().toStdString().c_str());
         statusBar()->showMessage(message);
     }
     else if (qDialog.textValue().toStdString() == "Phong")
     {
         input_mesh_visualizer_ptr->clearAndDeleteShaders();
         input_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodePhong.glsl");
         input_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodePhong.glsl");
         input_mesh_visualizer_ptr->installShaders();
         output_mesh_visualizer_ptr->clearAndDeleteShaders();
         output_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodePhong.glsl");
         output_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodePhong.glsl");
         output_mesh_visualizer_ptr->installShaders();
         QString message = tr(qDialog.textValue().toStdString().c_str());
         statusBar()->showMessage(message);
     }
     else if (qDialog.textValue().toStdString() == "Normal Map")
     {
         input_mesh_visualizer_ptr->clearAndDeleteShaders();
         input_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodeNormalMap.glsl");
         input_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodeNormalMap.glsl");
         input_mesh_visualizer_ptr->installShaders();
         output_mesh_visualizer_ptr->clearAndDeleteShaders();
         output_mesh_visualizer_ptr->addShader(GL_VERTEX_SHADER, "VertexShaderCodeNormalMap.glsl");
         output_mesh_visualizer_ptr->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodeNormalMap.glsl");
         output_mesh_visualizer_ptr->installShaders();
         QString message = tr(qDialog.textValue().toStdString().c_str());
         statusBar()->showMessage(message);
     }
 }
setSmoothingThread()
void myMainWindow::setSmoothingThread () private
setSmoothingThread - set thread for global smoothing
Definition at line 489 of file myMainWindow.cpp.
References GlobalSmoothingTask::current_thread, GlobalSmoothingTask::data, data, GlobalSmoothingTask::run(), smoothingTask, smoothingThread, and updateGlobalSmoothing().
Referenced by myMainWindow().
 {
     smoothingTask = new GlobalSmoothingTask;
     smoothingTask->moveToThread(&smoothingThread);
     smoothingTask->current_thread = &smoothingThread;
     connect(&smoothingThread, &QThread::started, smoothingTask, &GlobalSmoothingTask::run);
     connect(&smoothingThread, &QThread::finished, this, &myMainWindow::updateGlobalSmoothing);
     smoothingTask->data = &data;
 }
stopGlobalSmoothing()
void myMainWindow::stopGlobalSmoothing () private
stopGlobalSmoothing - stop global smoothing
Definition at line 499 of file myMainWindow.cpp.
References gs_status_stopping, and setGlobalSmoothingStatus().
Referenced by createActions().
 {
     setGlobalSmoothingStatus(gs_status_stopping);
 }
updateGlobalSmoothing()
void myMainWindow::updateGlobalSmoothing () private
updateGlobalSmoothing - global smoothing management (step by step)
Definition at line 529 of file myMainWindow.cpp.
References GlobalSmoothingTask::currentGlobalSmoothingIteration, data, GlobalSmoothingTask::finalGlobalSmoothingIteration, globalSmoothingStopped, gs_status_init, gs_status_stopped, output_mesh_visualizer_ptr, progress_bar, setGlobalSmoothingStatus(), smoothingTask, smoothingThread, GlobalSmoothingTask::updateData(), myGLWindow::updateMesh(), and myDataManager::updateShapes().
Referenced by setSmoothingThread().
 {
     int current_iteration = smoothingTask->currentGlobalSmoothingIteration;
     int final_iteration = smoothingTask->finalGlobalSmoothingIteration;
     if (globalSmoothingStopped)
     {
         if (current_iteration > 0)
         {
             smoothingTask->currentGlobalSmoothingIteration--;
             current_iteration--;
         }
         setGlobalSmoothingStatus(gs_status_stopped);
     }
     else if (current_iteration >= final_iteration)
     {
         smoothingTask->updateData();
         data.updateShapes();
         setGlobalSmoothingStatus(gs_status_init);
     }
     else
     {
         smoothingTask->updateData();
         data.updateShapes();
         smoothingTask->currentGlobalSmoothingIteration ++;
         smoothingThread.start();
     }
     output_mesh_visualizer_ptr->updateMesh();
     output_mesh_visualizer_ptr->repaint();
     progress_bar->setValue(static_cast<int>((static_cast<float>(current_iteration) / static_cast<float>(final_iteration))*100.0f));
 }
updateSelection()
void myMainWindow::updateSelection () private
updateSelection - update selection in data manager and visualization
Definition at line 746 of file myMainWindow.cpp.
References data, getSelection(), output_mesh_visualizer_ptr, radio_button_smoothing_type_f, runningStatus, myDataManager::selection, myGLWindow::setSelection(), and myDataManager::updateOutputSelection().
Referenced by eventFilter(), and keyPressEvent().
 {
     if (!runningStatus && radio_button_smoothing_type_f->isChecked())
     {
         vector<size_t> selected_vertices_ids;
         getSelection(selected_vertices_ids);
         data.updateOutputSelection(selected_vertices_ids);
         output_mesh_visualizer_ptr->setSelection(&data.selection);
         output_mesh_visualizer_ptr->repaint();
     }
 }
updateWidgetValues()
void myMainWindow::updateWidgetValues () private
updateWidgetValues - set default slider widget values (min, max and current)
Definition at line 212 of file myMainWindow.cpp.
References progress_bar, slider_fs_radius, slider_fs_smoothness, slider_gs_detail_preservation, slider_gs_radius_ratio, and slider_gs_smoothness.
Referenced by loadMesh().
 {
     progress_bar->setMaximum(100);
     progress_bar->setMinimum(0);
     progress_bar->setValue(0);
     slider_gs_smoothness->setMaximum(100);
     slider_gs_smoothness->setMinimum(0);
     slider_gs_smoothness->setValue(5);
     slider_gs_radius_ratio->setMaximum(100);
     slider_gs_radius_ratio->setMinimum(0);
     slider_gs_radius_ratio->setValue(10);
     slider_gs_detail_preservation->setMaximum(100);
     slider_gs_detail_preservation->setMinimum(0);
     slider_gs_detail_preservation->setValue(50);
     slider_fs_smoothness->setMaximum(50);
     slider_fs_smoothness->setMinimum(0);
     slider_fs_smoothness->setValue(3);
     slider_fs_radius->setMaximum(20);
     slider_fs_radius->setMinimum(0);
     slider_fs_radius->setValue(3);
 }
userGuide()
void myMainWindow::userGuide () private
userGuide - show user guide
Definition at line 418 of file myMainWindow.cpp.
Referenced by createActions().
 {
     QString link = "http://www.google.com";
     QDesktopServices::openUrl(QUrl(link));
 }
wireframeMode()
void myMainWindow::wireframeMode () private
wireframeMode - set wireframe rendering
Definition at line 278 of file myMainWindow.cpp.
References e_draw_wireframe, input_mesh_visualizer_ptr, output_mesh_visualizer_ptr, and myGLWindow::setVisualizationMode().
Referenced by createActions().
 {
     input_mesh_visualizer_ptr->setVisualizationMode(e_draw_wireframe);
     output_mesh_visualizer_ptr->setVisualizationMode(e_draw_wireframe);
 }
Field Documentation
aboutAct
QAction* myMainWindow::aboutAct private
Definition at line 124 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
alignmentGroup
QActionGroup* myMainWindow::alignmentGroup private
Menu Actions.
Definition at line 114 of file myMainWindow.h.
control_layout
QVBoxLayout* myMainWindow::control_layout private
layout for control widgets
Definition at line 77 of file myMainWindow.h.
Referenced by myMainWindow().
control_scroll_area
QScrollArea* myMainWindow::control_scroll_area private
scroll area for control widgets
Definition at line 76 of file myMainWindow.h.
Referenced by myMainWindow().
currentFocalizedSmoothingAlgorithm
focalizedSmoothingAlgorithm myMainWindow::currentFocalizedSmoothingAlgorithm private
focalized smoothing algorithm flag
Definition at line 133 of file myMainWindow.h.
Referenced by myMainWindow(), selectAndSmooth(), and setFocalizedSmoothingAlgorithm().
currentGlobalSmoothingAlgorithm
globalSmoothingAlgorithm myMainWindow::currentGlobalSmoothingAlgorithm private
global smoothing algorithm flag
Definition at line 132 of file myMainWindow.h.
Referenced by myMainWindow(), runGlobalSmoothing(), and setGlobalSmoothingAlgorithm().
data
myDataManager myMainWindow::data private
Data manager for iunput and output meshes
Definition at line 127 of file myMainWindow.h.
Referenced by getSelection(), loadMesh(), reinitializeOutput(), saveMesh(), selectAndSmooth(), setOutputAsInput(), setSmoothingThread(), updateGlobalSmoothing(), and updateSelection().
exitAct
QAction* myMainWindow::exitAct private
Definition at line 117 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
fileMenu
QMenu* myMainWindow::fileMenu private
file menu
Definition at line 108 of file myMainWindow.h.
Referenced by createMenus().
flatModeAct
QAction* myMainWindow::flatModeAct private
Definition at line 118 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
globalSmoothingStopped
bool myMainWindow::globalSmoothingStopped private
if global smoothing is stopped
Definition at line 138 of file myMainWindow.h.
Referenced by myMainWindow(), setGlobalSmoothingStatus(), and updateGlobalSmoothing().
group_box_data_manipulation
QGroupBox* myMainWindow::group_box_data_manipulation private
group box for data manipulation controls
Definition at line 82 of file myMainWindow.h.
Referenced by myMainWindow(), and setGlobalSmoothingStatus().
group_box_focalized_smoothing
QGroupBox* myMainWindow::group_box_focalized_smoothing private
group box for focalized smoothing controls
Definition at line 81 of file myMainWindow.h.
Referenced by enableSmoothingType(), and myMainWindow().
group_box_global_smoothing
QGroupBox* myMainWindow::group_box_global_smoothing private
group box for global smoothing controls
Definition at line 80 of file myMainWindow.h.
Referenced by enableSmoothingType(), and myMainWindow().
group_box_smoothing_type
QGroupBox* myMainWindow::group_box_smoothing_type private
group box for smoothing type selection
Definition at line 79 of file myMainWindow.h.
Referenced by myMainWindow(), and setGlobalSmoothingStatus().
helpMenu
QMenu* myMainWindow::helpMenu private
help menu
Definition at line 111 of file myMainWindow.h.
Referenced by createMenus().
input_mesh_visualizer_ptr
myGLWindow* myMainWindow::input_mesh_visualizer_ptr private
visualization widget for input mesh
Definition at line 71 of file myMainWindow.h.
Referenced by flatMode(), loadMesh(), myMainWindow(), pointsMode(), reinitializeOutput(), setOutputAsInput(), setShaders(), and wireframeMode().
layout
QHBoxLayout* myMainWindow::layout private
main layout contained in main window
Definition at line 75 of file myMainWindow.h.
Referenced by myMainWindow().
layout_data_manipulation
QHBoxLayout* myMainWindow::layout_data_manipulation private
Definition at line 89 of file myMainWindow.h.
Referenced by myMainWindow().
layout_focalized_smoothing
QVBoxLayout* myMainWindow::layout_focalized_smoothing private
Definition at line 88 of file myMainWindow.h.
Referenced by myMainWindow().
layout_global_smoothing
QVBoxLayout* myMainWindow::layout_global_smoothing private
Definition at line 86 of file myMainWindow.h.
Referenced by myMainWindow().
layout_global_smoothing_buttons
QHBoxLayout* myMainWindow::layout_global_smoothing_buttons private
Definition at line 87 of file myMainWindow.h.
Referenced by myMainWindow().
layout_smoothing_type
QHBoxLayout* myMainWindow::layout_smoothing_type private
Auxiliar Layouts.
Definition at line 85 of file myMainWindow.h.
Referenced by myMainWindow().
loadAct
QAction* myMainWindow::loadAct private
Definition at line 115 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
output_mesh_visualizer_ptr
myGLWindow* myMainWindow::output_mesh_visualizer_ptr private
visualization widget for output mesh
Definition at line 72 of file myMainWindow.h.
Referenced by eventFilter(), flatMode(), getSelection(), keyPressEvent(), loadMesh(), myMainWindow(), pointsMode(), reinitializeOutput(), removeSelection(), selectAndSmooth(), setOutputAsInput(), setShaders(), updateGlobalSmoothing(), updateSelection(), and wireframeMode().
pointsModeAct
QAction* myMainWindow::pointsModeAct private
Definition at line 120 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
progress_bar
QProgressBar* myMainWindow::progress_bar private
global smoothing progress bar
Definition at line 106 of file myMainWindow.h.
Referenced by myMainWindow(), setGlobalSmoothingStatus(), updateGlobalSmoothing(), and updateWidgetValues().
push_button_global_smoothing_continue
QPushButton* myMainWindow::push_button_global_smoothing_continue private
global smoothing continue button
Definition at line 96 of file myMainWindow.h.
Referenced by createActions(), myMainWindow(), and setGlobalSmoothingStatus().
push_button_global_smoothing_run
QPushButton* myMainWindow::push_button_global_smoothing_run private
global smoothing run button
Definition at line 94 of file myMainWindow.h.
Referenced by createActions(), myMainWindow(), and setGlobalSmoothingStatus().
push_button_global_smoothing_stop
QPushButton* myMainWindow::push_button_global_smoothing_stop private
global smoothing stop button
Definition at line 95 of file myMainWindow.h.
Referenced by createActions(), myMainWindow(), and setGlobalSmoothingStatus().
push_button_reinitialize_data
QPushButton* myMainWindow::push_button_reinitialize_data private
reinitialize button
Definition at line 97 of file myMainWindow.h.
Referenced by createActions(), and myMainWindow().
push_button_update_input_data
QPushButton* myMainWindow::push_button_update_input_data private
update button
Definition at line 98 of file myMainWindow.h.
Referenced by createActions(), and myMainWindow().
radio_button_smoothing_type_f
QRadioButton* myMainWindow::radio_button_smoothing_type_f private
smoothing type selection radio button focalized smoothing
Definition at line 92 of file myMainWindow.h.
Referenced by createActions(), myMainWindow(), selectAndSmooth(), and updateSelection().
radio_button_smoothing_type_g
QRadioButton* myMainWindow::radio_button_smoothing_type_g private
smoothing type selection radio button global smoothing
Definition at line 91 of file myMainWindow.h.
Referenced by createActions(), enableSmoothingType(), and myMainWindow().
runningStatus
bool myMainWindow::runningStatus private
if global smoothing is running
Definition at line 136 of file myMainWindow.h.
Referenced by myMainWindow(), selectAndSmooth(), setGlobalSmoothingStatus(), and updateSelection().
saveAct
QAction* myMainWindow::saveAct private
Definition at line 116 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
selectionMode
bool myMainWindow::selectionMode private
if user is selecting something in output mesh visualizer
Definition at line 135 of file myMainWindow.h.
Referenced by eventFilter(), keyPressEvent(), keyReleaseEvent(), and myMainWindow().
setFocalizedSmoothingAlgorithmAct
QAction* myMainWindow::setFocalizedSmoothingAlgorithmAct private
Definition at line 123 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
setGlobalSmoothingAlgorithmAct
QAction* myMainWindow::setGlobalSmoothingAlgorithmAct private
Definition at line 122 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
setShadersAct
QAction* myMainWindow::setShadersAct private
Definition at line 121 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
settingsMenu
QMenu* myMainWindow::settingsMenu private
settings menu
Definition at line 110 of file myMainWindow.h.
Referenced by createMenus().
slider_fs_radius
QSlider* myMainWindow::slider_fs_radius private
focalized smoothing radius slider
Definition at line 104 of file myMainWindow.h.
Referenced by getSelection(), myMainWindow(), and updateWidgetValues().
slider_fs_smoothness
QSlider* myMainWindow::slider_fs_smoothness private
focalized smoothing smoothness slider
Definition at line 103 of file myMainWindow.h.
Referenced by myMainWindow(), selectAndSmooth(), and updateWidgetValues().
slider_gs_detail_preservation
QSlider* myMainWindow::slider_gs_detail_preservation private
global smoothing detail preservation slider
Definition at line 102 of file myMainWindow.h.
Referenced by myMainWindow(), runGlobalSmoothing(), and updateWidgetValues().
slider_gs_radius_ratio
QSlider* myMainWindow::slider_gs_radius_ratio private
global smoothing radius ratio slider
Definition at line 101 of file myMainWindow.h.
Referenced by myMainWindow(), runGlobalSmoothing(), and updateWidgetValues().
slider_gs_smoothness
QSlider* myMainWindow::slider_gs_smoothness private
global smoothing smoothness slider
Definition at line 100 of file myMainWindow.h.
Referenced by myMainWindow(), runGlobalSmoothing(), and updateWidgetValues().
smoothingTask
GlobalSmoothingTask* myMainWindow::smoothingTask private
global smoothing external step task
Definition at line 130 of file myMainWindow.h.
Referenced by runGlobalSmoothing(), setSmoothingThread(), and updateGlobalSmoothing().
smoothingThread
QThread myMainWindow::smoothingThread private
thread for global smoothing
Definition at line 129 of file myMainWindow.h.
Referenced by continueGlobalSmoothing(), runGlobalSmoothing(), setSmoothingThread(), updateGlobalSmoothing(), and ~myMainWindow().
userGuideAct
QAction* myMainWindow::userGuideAct private
Definition at line 125 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
viewMenu
QMenu* myMainWindow::viewMenu private
view menu
Definition at line 109 of file myMainWindow.h.
Referenced by createMenus().
widget
QWidget* myMainWindow::widget private
main widget contained in main window
Definition at line 74 of file myMainWindow.h.
Referenced by myMainWindow().
wireframeModeAct
QAction* myMainWindow::wireframeModeAct private
Definition at line 119 of file myMainWindow.h.
Referenced by createActions(), and createMenus().
The documentation for this class was generated from the following files:
myMainWindow.h
myMainWindow.cpp