Mesh Smoothing Tool: myGLWindow Class Reference
myGLWindow Class Reference
The myGLWindow class - Qt Widget for OpenGL Designed to support only one shape and one selection at time. So in the containers of the renderer there are two shapes at position 0 and 1. The first one for the current shape and the second one for the current selection. This object adapts a renderer to a QT OpenGL Widget which manages a single OpenGL context. Also, it simplifies the usage of the renderer for the mesh smoothing application.
#include <myGLWindow.h>
Public Member Functions
myGLWindow (QWidget *parent=0)
myGLWindow - default constructor
~myGLWindow ()
~myGLWindow - destructor
void sendDataToOpenGL ()
sendDataToOpenGL - call sendDataToOpenGL of the renderer, in the current context
void setVisualizationMode (int mode)
setVisualizationMode - set rendering mode of the current shape
void setShape (ShapeData *_shape)
setShape - set a shape as current shape (removing previous shape)
void setSelection (ShapeData *_selection)
setSelection - set a selection as current selection (removing previous selection)
void removeSelection ()
removeSelection - remove current selection
void updateMesh ()
updateMesh - update vertex data of the current shape (resend vertex data)
void addShader (GLenum _shaderType, const string &_fileName)
addShader - add a shader to the renderer
void clearAndDeleteShaders ()
clearAndDeleteShaders - clear, deattach and delete shaders of the renderer
void installShaders ()
installShaders - call installShaders of the renderer, in the current context.
glm::vec2 getCurrentMousePosition ()
getCurrentMousePosition - get mouse position in the OpenGL Window (Qt Widget)
glm::vec3 getRayDirection (glm::vec2 &pos)
getRayDirection - call getRayDirection of the renderer for a given position
myCamera * getCamera ()
getCamera - get pointer to the camera of the renderer
glm::mat4 getModelToWorldMatrix ()
getModelToWorldMatrix - get model to world matrix applied to all objects in the renderer
Protected Member Functions
void initializeGL ()
initializeGL - initialize the renderer in the current OpenGL context
void paintGL ()
paintGL - call renderer draw functions
bool event (QEvent *event)
event - event manager for mouse interactions (in myGLWindow)
Private Attributes
myRenderer * renderer
renderer - renderer object for visualization in the widget
Detailed Description
The myGLWindow class - Qt Widget for OpenGL Designed to support only one shape and one selection at time. So in the containers of the renderer there are two shapes at position 0 and 1. The first one for the current shape and the second one for the current selection. This object adapts a renderer to a QT OpenGL Widget which manages a single OpenGL context. Also, it simplifies the usage of the renderer for the mesh smoothing application.
Definition at line 37 of file myGLWindow.h.
Constructor & Destructor Documentation
myGLWindow()
myGLWindow::myGLWindow (QWidget * parent = 0)
myGLWindow - default constructor
Parameters
parent parent widget pointer
Definition at line 3 of file myGLWindow.cpp.
 : QOpenGLWidget(parent)
 {
 }
~myGLWindow()
myGLWindow::~myGLWindow ()
~myGLWindow - destructor
Definition at line 9 of file myGLWindow.cpp.
References renderer.
 {
     delete renderer;
 }
Member Function Documentation
addShader()
void myGLWindow::addShader (GLenum _shaderType, const string & _fileName)
addShader - add a shader to the renderer
Parameters
_shaderType - shader type
_fileName - shader code file name
Definition at line 122 of file myGLWindow.cpp.
References myRenderer::addShader(), and renderer.
Referenced by myMainWindow::setShaders().
 {
     makeCurrent();
     renderer->addShader(_shaderType,_fileName);
     doneCurrent();
 }
clearAndDeleteShaders()
void myGLWindow::clearAndDeleteShaders ()
clearAndDeleteShaders - clear, deattach and delete shaders of the renderer
Definition at line 129 of file myGLWindow.cpp.
References myRenderer::clearAndDeleteShaders(), and renderer.
Referenced by myMainWindow::setShaders().
 {
     makeCurrent();
     renderer->clearAndDeleteShaders();
     doneCurrent();
 }
event()
bool myGLWindow::event (QEvent * event) protected
event - event manager for mouse interactions (in myGLWindow)
Parameters
event - input event
Returns
success
Definition at line 37 of file myGLWindow.cpp.
References renderer, myRenderer::rotateObjects(), myRenderer::translateCamera(), and myRenderer::zoom().
 {
     if (event->type() == QEvent::MouseMove) {
         QMouseEvent * e = static_cast<QMouseEvent *>(event);
         if (e->buttons() == Qt::LeftButton)
             renderer->rotateObjects(glm::vec2(e->x(), e->y()));
         if (e->buttons() == Qt::RightButton)
             renderer->translateCamera(glm::vec2(e->x(), e->y()));
         repaint();
         return true;
     }
     else if (event->type() == QEvent::Wheel)
     {
         QWheelEvent * e = static_cast<QWheelEvent *>(event);
         renderer->zoom(static_cast<float>(e->delta()));
         repaint();
         return true;
     }
     return QOpenGLWidget::event(event);
 }
getCamera()
myCamera * myGLWindow::getCamera ()
getCamera - get pointer to the camera of the renderer
Returns
camera pointer
Definition at line 153 of file myGLWindow.cpp.
References myRenderer::getCamera(), and renderer.
Referenced by myMainWindow::getSelection().
 {
     return renderer->getCamera();
 }
getCurrentMousePosition()
glm::vec2 myGLWindow::getCurrentMousePosition ()
getCurrentMousePosition - get mouse position in the OpenGL Window (Qt Widget)
Returns
mouse position
Definition at line 143 of file myGLWindow.cpp.
Referenced by myMainWindow::getSelection().
 {
     QPoint p = mapFromGlobal(QCursor::pos()); return glm::vec2(p.x(), p.y());
 }
getModelToWorldMatrix()
glm::mat4 myGLWindow::getModelToWorldMatrix ()
getModelToWorldMatrix - get model to world matrix applied to all objects in the renderer
Returns
4x4 model to world matrix
Definition at line 158 of file myGLWindow.cpp.
References myRenderer::getModelToWorldMatrix(), and renderer.
Referenced by myMainWindow::getSelection().
 {
     return renderer->getModelToWorldMatrix();
 }
getRayDirection()
glm::vec3 myGLWindow::getRayDirection (glm::vec2 & pos)
getRayDirection - call getRayDirection of the renderer for a given position
Parameters
pos - position
Returns
ray direction
Definition at line 148 of file myGLWindow.cpp.
References myRenderer::getRayDirection(), and renderer.
Referenced by myMainWindow::getSelection().
 {
     return renderer->getRayDirection(pos);
 }
initializeGL()
void myGLWindow::initializeGL () protected
initializeGL - initialize the renderer in the current OpenGL context
Definition at line 21 of file myGLWindow.cpp.
References myRenderer::addShader(), myRenderer::initialize(), and renderer.
 {
     renderer = new myRenderer;
     setMouseTracking(true);
     renderer->addShader(GL_VERTEX_SHADER, "VertexShaderCodePhong.glsl");
     renderer->addShader(GL_FRAGMENT_SHADER, "FragmentShaderCodePhong.glsl");
     renderer->initialize();
 }
installShaders()
void myGLWindow::installShaders ()
installShaders - call installShaders of the renderer, in the current context.
Definition at line 136 of file myGLWindow.cpp.
References myRenderer::installShaders(), and renderer.
Referenced by myMainWindow::setShaders().
 {
     makeCurrent();
     renderer->installShaders();
     doneCurrent();
 }
paintGL()
void myGLWindow::paintGL () protected
paintGL - call renderer draw functions
Definition at line 30 of file myGLWindow.cpp.
References myRenderer::draw(), renderer, myRenderer::setHeight(), and myRenderer::setWidth().
 {
     renderer->setWidth(width());
     renderer->setHeight(height());
     renderer->draw();
 }
removeSelection()
void myGLWindow::removeSelection ()
removeSelection - remove current selection
Definition at line 78 of file myGLWindow.cpp.
References myRenderer::getNumberOfShapes(), myRenderer::removeShape(), renderer, and myRenderer::resendDataSingleBuffer().
Referenced by myMainWindow::removeSelection().
 {
     if (renderer->getNumberOfShapes() > 1)
     {
         renderer->removeShape(1);
         makeCurrent();
         renderer->resendDataSingleBuffer();
         doneCurrent();
         repaint();
     }
     else
     {
         repaint();
     }
 }
sendDataToOpenGL()
void myGLWindow::sendDataToOpenGL ()
sendDataToOpenGL - call sendDataToOpenGL of the renderer, in the current context
Definition at line 14 of file myGLWindow.cpp.
References renderer, and myRenderer::sendDataSingleBuffer().
 {
     makeCurrent();
     renderer->sendDataSingleBuffer();
     doneCurrent();
 }
setSelection()
void myGLWindow::setSelection (ShapeData * _selection)
setSelection - set a selection as current selection (removing previous selection)
Parameters
_selection new selection
Definition at line 94 of file myGLWindow.cpp.
References myRenderer::addShape(), e_draw_selection, myRenderer::getNumberOfShapes(), myRenderer::removeShape(), renderer, and myRenderer::resendDataSingleBuffer().
Referenced by myMainWindow::selectAndSmooth(), and myMainWindow::updateSelection().
 {
     if (renderer->getNumberOfShapes() <= 1)
     {
         renderer->addShape(_selection, e_draw_selection);
     }
     else
     {
         renderer->removeShape(1);
         renderer->addShape(_selection,e_draw_selection);
     }
     makeCurrent();
     renderer->resendDataSingleBuffer();
     doneCurrent();
     repaint();
 }
setShape()
void myGLWindow::setShape (ShapeData * _shape)
setShape - set a shape as current shape (removing previous shape)
Parameters
_shape new shape
Definition at line 67 of file myGLWindow.cpp.
References myRenderer::addShape(), myRenderer::clearShapes(), renderer, myRenderer::resendDataSingleBuffer(), and myRenderer::setDefaultValues().
Referenced by myMainWindow::loadMesh().
 {
     renderer->clearShapes();
     renderer->addShape(_shape);
     makeCurrent();
     renderer->resendDataSingleBuffer();
     doneCurrent();
     renderer->setDefaultValues();
     repaint();
 }
setVisualizationMode()
void myGLWindow::setVisualizationMode (int mode)
setVisualizationMode - set rendering mode of the current shape
Parameters
mode - input rendering mode
Definition at line 58 of file myGLWindow.cpp.
References myRenderer::getNumberOfShapes(), renderer, and myRenderer::setShapeDrawMode().
Referenced by myMainWindow::flatMode(), myMainWindow::pointsMode(), and myMainWindow::wireframeMode().
 {
     if (renderer->getNumberOfShapes() > 0)
     {
         renderer->setShapeDrawMode(0, (myDrawFlags)mode);
         repaint();
     }
 }
updateMesh()
void myGLWindow::updateMesh ()
updateMesh - update vertex data of the current shape (resend vertex data)
Definition at line 111 of file myGLWindow.cpp.
References myRenderer::getNumberOfShapes(), renderer, and myRenderer::updateVertexBuffer().
Referenced by myMainWindow::reinitializeOutput(), myMainWindow::setOutputAsInput(), and myMainWindow::updateGlobalSmoothing().
 {
     if (renderer->getNumberOfShapes() > 0)
     {
         makeCurrent();
         renderer->updateVertexBuffer(0);
         doneCurrent();
         repaint();
     }
 }
Field Documentation
renderer
myRenderer* myGLWindow::renderer private
renderer - renderer object for visualization in the widget
Definition at line 42 of file myGLWindow.h.
Referenced by addShader(), clearAndDeleteShaders(), event(), getCamera(), getModelToWorldMatrix(), getRayDirection(), initializeGL(), installShaders(), paintGL(), removeSelection(), sendDataToOpenGL(), setSelection(), setShape(), setVisualizationMode(), updateMesh(), and ~myGLWindow().
The documentation for this class was generated from the following files:
myGLWindow.h
myGLWindow.cpp