Mesh Smoothing Tool: GlobalSmoothingTask Class Reference
GlobalSmoothingTask Class Reference
The GlobalSmoothingTask class - global smoothing task.
#include <smoothing.h>
Public Member Functions
void run ()
run - run current algorithm
void finishThread ()
finishThread - finalize the current thread
void updateData ()
updateData - set the current partial result as output mesh
Data Fields
int currentGlobalSmoothingIteration
currentGlobalSmoothingIteration - current global smoothing external iteration
int finalGlobalSmoothingIteration
finalGlobalSmoothingIteration - final global smoothing external iteration
int n_vertex_iterations
n_vertex_iterations - number of vertex iterations for vertex updating step
int iteration_step_size
iteration_step_size - number of normal filtering iterations for each step (internal iterations)
float sigma_c_ratio
sigma_c_ratio - current
float sigma_s
sigma_s - current
TriMesh result
result - current partial result
QThread * current_thread
current_thread - thread where this task is running
myDataManager * data
data - data manager pointer
int algorithm_flag
algorithm_flag - current algotihm flag
Detailed Description
The GlobalSmoothingTask class - global smoothing task.
Definition at line 11 of file smoothing.h.
Member Function Documentation
finishThread()
void GlobalSmoothingTask::finishThread () inline
finishThread - finalize the current thread
Definition at line 70 of file smoothing.h.
Referenced by run().
     {
         current_thread->quit();
     }
run()
void GlobalSmoothingTask::run () inline
run - run current algorithm
Definition at line 58 of file smoothing.h.
References bilateralNormal(), finishThread(), guided(), and myDataManager::output_mesh.
Referenced by myMainWindow::setSmoothingThread().
                {
         if (algorithm_flag == 0)
             result = bilateralNormal(data->output_mesh, iteration_step_size, n_vertex_iterations, sigma_c_ratio, sigma_s);
         else if (algorithm_flag == 1)
             result = guided(data->output_mesh, iteration_step_size, n_vertex_iterations, sigma_c_ratio, sigma_s, 1.5f);
         else
             result = bilateralNormal(data->output_mesh, iteration_step_size, n_vertex_iterations, sigma_c_ratio, sigma_s);
         finishThread();
     }
updateData()
void GlobalSmoothingTask::updateData () inline
updateData - set the current partial result as output mesh
Definition at line 77 of file smoothing.h.
References myDataManager::output_mesh, and result.
Referenced by myMainWindow::updateGlobalSmoothing().
     {
         data->output_mesh = result;
     }
Field Documentation
algorithm_flag
int GlobalSmoothingTask::algorithm_flag
algorithm_flag - current algotihm flag
Definition at line 53 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing().
current_thread
QThread* GlobalSmoothingTask::current_thread
current_thread - thread where this task is running
Definition at line 45 of file smoothing.h.
Referenced by myMainWindow::setSmoothingThread().
currentGlobalSmoothingIteration
int GlobalSmoothingTask::currentGlobalSmoothingIteration
currentGlobalSmoothingIteration - current global smoothing external iteration
Definition at line 17 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing(), and myMainWindow::updateGlobalSmoothing().
data
myDataManager* GlobalSmoothingTask::data
data - data manager pointer
Definition at line 49 of file smoothing.h.
Referenced by myMainWindow::setSmoothingThread().
finalGlobalSmoothingIteration
int GlobalSmoothingTask::finalGlobalSmoothingIteration
finalGlobalSmoothingIteration - final global smoothing external iteration
Definition at line 21 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing(), and myMainWindow::updateGlobalSmoothing().
iteration_step_size
int GlobalSmoothingTask::iteration_step_size
iteration_step_size - number of normal filtering iterations for each step (internal iterations)
Definition at line 29 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing().
n_vertex_iterations
int GlobalSmoothingTask::n_vertex_iterations
n_vertex_iterations - number of vertex iterations for vertex updating step
Definition at line 25 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing().
result
TriMesh GlobalSmoothingTask::result
result - current partial result
Definition at line 41 of file smoothing.h.
Referenced by updateData().
sigma_c_ratio
float GlobalSmoothingTask::sigma_c_ratio
sigma_c_ratio - current
Definition at line 33 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing().
sigma_s
float GlobalSmoothingTask::sigma_s
sigma_s - current
Definition at line 37 of file smoothing.h.
Referenced by myMainWindow::runGlobalSmoothing().
The documentation for this class was generated from the following file:
smoothing.h