Mesh Smoothing Tool: Mesh Processing
Mesh Processing
Mesh denoising functions.
Data Structures
struct MyTraits
The MyTraits struct - OpenMesh custom traits.
Typedefs
typedef OpenMesh::TriMesh_ArrayKernelT< MyTraits > TriMesh
TriMesh - triangular mesh definition.
typedef float num_t
num_t - type definition for numbers used in mesh processing module
Enumerations
enum FaceNeighborType { kVertexBased, kEdgeBased, kRadiusBased }
The FaceNeighborType enum - determines the face neighborhood features.
Functions
void updateVertexPositions (TriMesh &mesh, vector< TriMesh::Normal > &filtered_normals, int iteration_number, bool fixed_boundary)
updateVertexPositions - computes new vertex positions adapted to an input normal field.
num_t getSigmaC (TriMesh &mesh, vector< TriMesh::Point > &face_centroids, num_t sigma_c_scalar)
getSigmaC - sigma_c computation based on the average of face centroid distances (only between adjacent faces), and multiplied by a scalar
num_t getRadius (TriMesh &mesh, num_t scalar)
getRadius - computation of radius for radius-based face neighborhood, based on the average of face centroid distances (only between adjacent faces) and multiplied by a scalar
TriMesh uniformLaplacian (TriMesh &_mesh, int iteration_number, num_t scale)
Uniform Laplacian smoothing.
TriMesh uniformLaplacian (TriMesh &_mesh, int iteration_number, num_t scale, vector< size_t > &vertex_ids)
uniformLaplacian - denoise a subset of vertices of an input mesh using Uniform Laplacian Smoothing Algorithm
TriMesh HCLaplacian (TriMesh &_mesh, int iteration_number, num_t alpha, num_t beta)
HC Laplacian smoothing (Vollmer et al.)
TriMesh HCLaplacian (TriMesh &_mesh, int iteration_number, num_t alpha, num_t beta, vector< size_t > &vertex_ids)
HCLaplacian - denoise a subset of vertices of an input mesh using HC Laplacian Smoothing Algorithm.
void updateFilteredNormals (TriMesh &mesh, int normal_iteration_number, num_t sigma_c_scalar, num_t sigma_s, vector< TriMesh::Normal > &filtered_normals)
Bilateral normal filtering for mesh denoising (Zheng et al.)
TriMesh bilateralNormal (TriMesh &_mesh, int normal_iteration_number, int vertex_iteration_number, num_t sigma_c_scalar, num_t sigma_s)
bilateralNormal - Denoise the input mesh using Bilateral Normal Filtering Algorithm
void getAllFaceNeighborsGMNF (TriMesh &mesh, FaceNeighborType face_neighbor_type, num_t radius, bool include_central_face, vector< vector< TriMesh::FaceHandle > > &all_face_neighbors)
Guided mesh normal filtering (Zhang et al.)
void getAllGuidedNeighborsGMNF (TriMesh &mesh, vector< vector< TriMesh::FaceHandle > > &all_guided_neighbors)
getAllGuidedNeighborsGMNF - neighborhood computation for guidance signal
void getFaceNeighborsInnerEdges (TriMesh &mesh, vector< TriMesh::FaceHandle > &face_neighbors, vector< TriMesh::EdgeHandle > &inner_edges)
getFaceNeighborsInnerEdges - get all inner edges of a face neighborhood
void getConsistenciesAndMeanNormals (TriMesh &mesh, vector< vector< TriMesh::FaceHandle > > &all_guided_neighbors, vector< num_t > &face_areas, vector< TriMesh::Normal > &normals, vector< pair< num_t, TriMesh::Normal > > &consistencies_and_mean_normals)
getConsistenciesAndMeanNormals - consistency and mean normal computation for all patches
void getGuidedNormals (TriMesh &mesh, vector< vector< TriMesh::FaceHandle > > &all_guided_neighbors, vector< num_t > &face_areas, vector< TriMesh::Normal > &normals, vector< pair< num_t, TriMesh::Normal > > consistencies_and_mean_normals, vector< TriMesh::Normal > &guided_normals)
getGuidedNormals - guided normal computation for each face of the mesh
void updateFilteredNormalsGuided (TriMesh &mesh, vector< TriMesh::Normal > &filtered_normals, num_t radius_scalar, num_t sigma_c_scalar, int normal_iteration_number, num_t sigma_s, int vertex_iteration_number)
updateFilteredNormalsGuided - guided bilateral filtering of a normal field (face based) of a mesh
TriMesh guided (TriMesh _mesh, int normal_iteration_number, int vertex_iteration_number, num_t sigma_c_scalar, num_t sigma_s, num_t radius_scalar)
guided - Denoise the input mesh using Guided Mesh Normal Filtering Algorithm
bool importMesh (TriMesh &mesh, string filename)
importMesh - read mesh file (.obj, .off, .ply, .stl)
bool exportMesh (TriMesh &mesh, string filename)
exportMesh - write mesh file (.obj, .off, .ply, .stl)
void getVertexNeighbors (TriMesh &mesh, TriMesh::VertexHandle vh, int k, vector< TriMesh::VertexHandle > &vertex_neighbors)
Vertex neighborhood.
void getAdaptiveVertexNeighbors (TriMesh &mesh, TriMesh::VertexHandle vh, num_t radius, vector< TriMesh::VertexHandle > &vertex_neighbors)
getAdaptiveVertexNeighbors: get all neighboring vertices of a given vertex regarding a radius
void getAllVertexNeighbors (TriMesh &mesh, int k, vector< vector< TriMesh::VertexHandle > > &all_vertex_neighbors)
getAllVertexNeighbors: get all neighboring vertices of all vertices regarding a depth k (k-ring)
void getAllAdaptiveVertexNeighbors (TriMesh &mesh, num_t radius, vector< vector< TriMesh::VertexHandle > > &all_vertex_neighbors)
getAllAdaptiveVertexNeighbors: get all neighboring vertices of all vertices regarding a radius
void getFaceNeighbors_EdgeBased (TriMesh &mesh, TriMesh::FaceHandle fh, vector< TriMesh::FaceHandle > &face_neighbors)
Face neighborhood.
void getFaceNeighbors_VertexBased (TriMesh &mesh, TriMesh::FaceHandle fh, vector< TriMesh::FaceHandle > &face_neighbors)
getFaceNeighbors_VertexBased: get neighboring faces based on face vertices
void getFaceNeighbors_RadiusBased (TriMesh &mesh, TriMesh::FaceHandle fh, num_t radius, vector< TriMesh::FaceHandle > &face_neighbors)
getFaceNeighbors_RadiusBased: get neighboring faces regarding a radius
void getAllFaceNeighbors_EdgeBased (TriMesh &mesh, bool include_target_face, vector< vector< TriMesh::FaceHandle > > &all_face_neighbors)
getAllFaceNeighbors_EdgeBased: get all neighboring faces of all faces (edge based)
void getAllFaceNeighbors_VertexBased (TriMesh &mesh, bool include_target_face, vector< vector< TriMesh::FaceHandle > > &all_face_neighbors)
getAllFaceNeighbors_VertexBased: get all neighboring faces of all faces (vertex based)
num_t getArea (TriMesh &mesh)
getArea - area computation of a mesh (sum of triangle areas)
num_t getVolume (TriMesh &mesh)
getVolume - volume computation of a mesh
num_t getAverageEdgeLength (TriMesh &mesh)
getAverageEdgeLength - average edge length computation of a mesh
void getAllFaceAreas (TriMesh &mesh, vector< num_t > &areas)
getAllFaceAreas - area computation for all faces
void getAllFaceCentroids (TriMesh &mesh, vector< TriMesh::Point > &centroids)
getAllFaceCentroids - centroid computation for all faces
void getAllFaceNormals (TriMesh &mesh, vector< TriMesh::Normal > &normals)
getAllFaceNormals - normal computation for all faces
void getFaceVertexAngle (TriMesh &mesh, TriMesh::FaceHandle fh, TriMesh::VertexHandle vh, num_t &angle)
getFaceVertexAngle - angle computation for a given vertex included in a face
num_t getVertexArea (TriMesh &mesh, TriMesh::VertexHandle vh, vector< num_t > &areas)
getVertexArea - vertex area computation (barycentric area)
void getAllVertexAreas (TriMesh &mesh, vector< num_t > &areas)
getAllVertexAreas - vertex area computation for all vertices (barycentric areas)
void getAllPoints (TriMesh &mesh, vector< TriMesh::Point > &points)
getAllPoints - get all vertex coordinates
num_t GaussianWeight (num_t distance, num_t sigma)
GaussianWeight - gaussian function computation used for bilateral filtering.
num_t NormalDistance (const TriMesh::Normal &n1, const TriMesh::Normal &n2)
NormalDistance - computation of normal distance: .
Detailed Description
Mesh denoising functions.
Mesh processing auxiliar functions.
Mesh processing neighborhood functions.
Mesh processing half-edge data structure definition (OpenMesh library).
Mesh processing I/O functions (OpenMesh library).
Module containing mesh processing tools useful for the application
Typedef Documentation
num_t
typedef float num_t
num_t - type definition for numbers used in mesh processing module
Definition at line 49 of file mesh.h.
TriMesh
typedef OpenMesh::TriMesh_ArrayKernelT<MyTraits> TriMesh
TriMesh - triangular mesh definition.
Definition at line 44 of file mesh.h.
Enumeration Type Documentation
FaceNeighborType
enum FaceNeighborType
The FaceNeighborType enum - determines the face neighborhood features.
Enumerator
kVertexBased
vertex based face neighborhood
kEdgeBased
edge based face neighborhood
kRadiusBased
radius based face neighborhood
Definition at line 18 of file denoising.h.
                      {
     kVertexBased,
     kEdgeBased,
     kRadiusBased
 };
Function Documentation
bilateralNormal()
TriMesh bilateralNormal (TriMesh & _mesh, int normal_iteration_number, int vertex_iteration_number, num_t sigma_c_scalar, num_t sigma_s)
bilateralNormal - Denoise the input mesh using Bilateral Normal Filtering Algorithm
Parameters
_mesh input mesh
normal_iteration_number number of iterations for normal field filtering
vertex_iteration_number number of iterations for vertex updating
sigma_c_scalar bilateral normal field filtering influence regarding a based on average edge length (spatial distance influence)
sigma_s bilateral normal field filtering parameter
Returns
denoised mesh
Definition at line 327 of file denoising.cpp.
References updateFilteredNormals(), and updateVertexPositions().
Referenced by GlobalSmoothingTask::run().
 {
     TriMesh mesh = _mesh;
     vector<TriMesh::Normal> filtered_normals;
     updateFilteredNormals(mesh, normal_iteration_number, sigma_c_scalar, sigma_s, filtered_normals);
     updateVertexPositions(mesh, filtered_normals, vertex_iteration_number, true);
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
exportMesh()
bool exportMesh (TriMesh & mesh, string filename)
exportMesh - write mesh file (.obj, .off, .ply, .stl)
Parameters
mesh - input mesh
filename - output file name
Returns
success
Definition at line 12 of file iomesh.cpp.
Referenced by myDataManager::saveOutputMesh().
 {
     OpenMesh::IO::Options opt;
     //opt += OpenMesh::IO::Options::VertexColor;
     return OpenMesh::IO::write_mesh(mesh, filename,opt);
 }
GaussianWeight()
num_t GaussianWeight (num_t distance, num_t sigma) inline
GaussianWeight - gaussian function computation used for bilateral filtering.
Parameters
distance input distance
sigma input sigma
Returns
function value for inputs (distance and sigma)
Definition at line 98 of file util.h.
Referenced by updateFilteredNormals(), and updateFilteredNormalsGuided().
 {
     return static_cast<num_t>(exp( -0.5 * distance * distance / (sigma * sigma)));
 }
getAdaptiveVertexNeighbors()
void getAdaptiveVertexNeighbors (TriMesh & mesh, TriMesh::VertexHandle vh, num_t radius, vector< TriMesh::VertexHandle > & vertex_neighbors)
getAdaptiveVertexNeighbors: get all neighboring vertices of a given vertex regarding a radius
Parameters
mesh input mesh
vh evaluated vertex
radius radius
vertex_neighbors vector containing neighbors (output)
Definition at line 42 of file neighborhood.cpp.
Referenced by getAllAdaptiveVertexNeighbors().
 {
     vertex_neighbors.clear();
     vector<bool> mark(mesh.n_vertices(),false);
     queue<TriMesh::VertexHandle> queue_vertex_handle;
     mark[vh.idx()] = true;
     queue_vertex_handle.push(vh);
     TriMesh::Point ci = mesh.point(vh);
     while(!queue_vertex_handle.empty())
     {
         TriMesh::VertexHandle vh = queue_vertex_handle.front();
         vertex_neighbors.push_back(vh);
         queue_vertex_handle.pop();
         for(TriMesh::VertexVertexIter vv_it = mesh.vv_iter(vh); vv_it.is_valid(); ++vv_it)
         {
             TriMesh::VertexHandle vh_neighbor = *vv_it;
             if(mark[vh_neighbor.idx()] == false)
             {
                 TriMesh::Point cj = mesh.point(vh_neighbor);
                 num_t length = (cj - ci).length();
                 if(length <= radius)
                     queue_vertex_handle.push(vh_neighbor);
                 mark[vh_neighbor.idx()] = true;
             }
         }
     }
 }
getAllAdaptiveVertexNeighbors()
void getAllAdaptiveVertexNeighbors (TriMesh & mesh, num_t radius, vector< vector< TriMesh::VertexHandle > > & all_vertex_neighbors)
getAllAdaptiveVertexNeighbors: get all neighboring vertices of all vertices regarding a radius
Parameters
mesh input mesh
radius radius
all_vertex_neighbors vector containing all neighbor vectors (output)
Definition at line 83 of file neighborhood.cpp.
References getAdaptiveVertexNeighbors().
 {
     all_vertex_neighbors.resize(mesh.n_vertices());
     for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
     {
         vector<TriMesh::VertexHandle> vertex_neighbor;
         getAdaptiveVertexNeighbors(mesh, *v_it, radius, vertex_neighbor);
         all_vertex_neighbors[v_it->idx()] = vertex_neighbor;
     }
 }
getAllFaceAreas()
void getAllFaceAreas (TriMesh & mesh, vector< num_t > & areas)
getAllFaceAreas - area computation for all faces
Parameters
mesh input mesh
areas output vector containing areas for all faces
Definition at line 54 of file util.cpp.
Referenced by getAllVertexAreas(), getArea(), updateFilteredNormals(), and updateFilteredNormalsGuided().
 {
     areas.resize(mesh.n_faces());
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         vector<TriMesh::Point> point;
         point.resize(3); int index = 0;
         for(TriMesh::FaceVertexIter fv_it = mesh.fv_iter(*f_it); fv_it.is_valid(); fv_it++)
         {
             point[index] = mesh.point(*fv_it);
             index++;
         }
         TriMesh::Point edge1 = point[1] - point[0];
         TriMesh::Point edge2 = point[1] - point[2];
         num_t S = 0.5f * (edge1 % edge2).length();
         areas[(*f_it).idx()] = S;
     }
 }
getAllFaceCentroids()
void getAllFaceCentroids (TriMesh & mesh, vector< TriMesh::Point > & centroids)
getAllFaceCentroids - centroid computation for all faces
Parameters
mesh input mesh
centroids output vector containing centroids for all faces
Definition at line 74 of file util.cpp.
Referenced by getRadius(), updateFilteredNormals(), updateFilteredNormalsGuided(), and updateVertexPositions().
 {
     centroids.resize(mesh.n_faces(), TriMesh::Point(0.0, 0.0, 0.0));
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         TriMesh::Point pt = mesh.calc_face_centroid(*f_it);
         centroids[(*f_it).idx()] = pt;
     }
 }
getAllFaceNeighbors_EdgeBased()
void getAllFaceNeighbors_EdgeBased (TriMesh & mesh, bool include_target_face, vector< vector< TriMesh::FaceHandle > > & all_face_neighbors)
getAllFaceNeighbors_EdgeBased: get all neighboring faces of all faces (edge based)
Parameters
mesh input mesh
include_target_face include fh as neighbor
all_face_neighbors vector containing neighbors (output)
Definition at line 157 of file neighborhood.cpp.
References getFaceNeighbors_EdgeBased().
 {
     all_face_neighbors.resize(mesh.n_faces());
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         vector<TriMesh::FaceHandle> face_neighbors;
         getFaceNeighbors_EdgeBased(mesh, *f_it, face_neighbors);
         if(include_target_face) face_neighbors.push_back(*f_it); //include target face
         all_face_neighbors[f_it->idx()] = face_neighbors;
     }
 }
getAllFaceNeighbors_VertexBased()
void getAllFaceNeighbors_VertexBased (TriMesh & mesh, bool include_target_face, vector< vector< TriMesh::FaceHandle > > & all_face_neighbors)
getAllFaceNeighbors_VertexBased: get all neighboring faces of all faces (vertex based)
Parameters
mesh input mesh
include_target_face include fh as neighbor
all_face_neighbors vector containing neighbors (output)
Definition at line 169 of file neighborhood.cpp.
References getFaceNeighbors_VertexBased().
Referenced by updateFilteredNormals().
 {
     all_face_neighbors.resize(mesh.n_faces());
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         vector<TriMesh::FaceHandle> face_neighbors;
         getFaceNeighbors_VertexBased(mesh, *f_it, face_neighbors);
         if(include_target_face) face_neighbors.push_back(*f_it); //include target face
         all_face_neighbors[f_it->idx()] = face_neighbors;
     }
 }
getAllFaceNeighborsGMNF()
void getAllFaceNeighborsGMNF (TriMesh & mesh, FaceNeighborType face_neighbor_type, num_t radius, bool include_central_face, vector< vector< TriMesh::FaceHandle > > & all_face_neighbors)
Guided mesh normal filtering (Zhang et al.)
getAllFaceNeighborsGMNF - neighborhood computation for all mesh faces (for bilateral filtering)
Parameters
mesh input mesh
face_neighbor_type type of neighborhood to be considered
radius radius for radius based face neighborhood
include_central_face if the same face is considered as a neighbor
all_face_neighbors output vector containing neighboring faces IDs for each face of the mesh
Definition at line 344 of file denoising.cpp.
References getFaceNeighbors_RadiusBased(), getFaceNeighbors_VertexBased(), kRadiusBased, and kVertexBased.
Referenced by updateFilteredNormalsGuided().
 {
     vector<TriMesh::FaceHandle> face_neighbors;
     for (TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         if (face_neighbor_type == kVertexBased)
             getFaceNeighbors_VertexBased(mesh, *f_it, face_neighbors);
         else if (face_neighbor_type == kRadiusBased)
             getFaceNeighbors_RadiusBased(mesh, *f_it, radius, face_neighbors);
         if (include_central_face)
             face_neighbors.push_back(*f_it);
         all_face_neighbors[f_it->idx()] = face_neighbors;
     }
 }
getAllFaceNormals()
void getAllFaceNormals (TriMesh & mesh, vector< TriMesh::Normal > & normals)
getAllFaceNormals - normal computation for all faces
Parameters
mesh input mesh
normals vector containing normals for all faces
Definition at line 84 of file util.cpp.
Referenced by updateFilteredNormals(), and updateFilteredNormalsGuided().
 {
     mesh.request_face_normals();
     mesh.update_face_normals();
     normals.resize(mesh.n_faces());
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         TriMesh::Normal n = mesh.normal(*f_it);
         normals[f_it->idx()] = n;
     }
 }
getAllGuidedNeighborsGMNF()
void getAllGuidedNeighborsGMNF (TriMesh & mesh, vector< vector< TriMesh::FaceHandle > > & all_guided_neighbors)
getAllGuidedNeighborsGMNF - neighborhood computation for guidance signal
Parameters
mesh input mesh
all_guided_neighbors output vector containing neighboring faces IDs for each face of the mesh
Definition at line 361 of file denoising.cpp.
References getFaceNeighbors_VertexBased().
Referenced by updateFilteredNormalsGuided().
 {
     vector<TriMesh::FaceHandle> face_neighbors;
     for (TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         getFaceNeighbors_VertexBased(mesh, *f_it, face_neighbors);
         face_neighbors.push_back(*f_it);
         all_guided_neighbors[f_it->idx()] = face_neighbors;
     }
 }
getAllPoints()
void getAllPoints (TriMesh & mesh, vector< TriMesh::Point > & points)
getAllPoints - get all vertex coordinates
Parameters
mesh input mesh
points all vertex coordinates
Definition at line 135 of file util.cpp.
Referenced by HCLaplacian().
 {
     points.resize(mesh.n_vertices());
     for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
     {
         TriMesh::Point p = mesh.point(*v_it);
         points[v_it->idx()] = p;
     }
 }
getAllVertexAreas()
void getAllVertexAreas (TriMesh & mesh, vector< num_t > & areas)
getAllVertexAreas - vertex area computation for all vertices (barycentric areas)
Parameters
mesh input mesh
areas output vector containing all vertex areas
Definition at line 126 of file util.cpp.
References getAllFaceAreas(), and getVertexArea().
 {
     areas.resize(mesh.n_vertices());
     vector<num_t> face_areas;
     getAllFaceAreas(mesh,face_areas);
     for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
         areas[v_it->idx()]=getVertexArea(mesh,*v_it,face_areas);
 }
getAllVertexNeighbors()
void getAllVertexNeighbors (TriMesh & mesh, int k, vector< vector< TriMesh::VertexHandle > > & all_vertex_neighbors)
getAllVertexNeighbors: get all neighboring vertices of all vertices regarding a depth k (k-ring)
Parameters
mesh input mesh
k depth
all_vertex_neighbors vector containing all neighbor vectors (output)
Definition at line 72 of file neighborhood.cpp.
References getVertexNeighbors().
 {
     all_vertex_neighbors.resize(mesh.n_vertices());
     for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
     {
         vector<TriMesh::VertexHandle> vertex_neighbor;
         getVertexNeighbors(mesh, *v_it, k, vertex_neighbor);
         all_vertex_neighbors[v_it->idx()] = vertex_neighbor;
     }
 }
getArea()
num_t getArea (TriMesh & mesh)
getArea - area computation of a mesh (sum of triangle areas)
Parameters
mesh input mesh
Returns
total area
Definition at line 3 of file util.cpp.
References getAllFaceAreas().
 {
     vector<num_t> areas;
     getAllFaceAreas(mesh,areas);
     num_t sum = 0;
     for (size_t i=0;i<areas.size();i++)
         sum+=areas[i];
     return sum;
 }
getAverageEdgeLength()
num_t getAverageEdgeLength (TriMesh & mesh)
getAverageEdgeLength - average edge length computation of a mesh
Parameters
mesh input mesh
Returns
average edge length
Definition at line 43 of file util.cpp.
 {
     num_t average_edge_length = 0.0;
     for(TriMesh::EdgeIter e_it = mesh.edges_begin(); e_it != mesh.edges_end(); e_it++)
         average_edge_length += mesh.calc_edge_length(*e_it);
     num_t edgeNum = (num_t)mesh.n_edges();
     average_edge_length /= edgeNum;
     return average_edge_length;
 }
getConsistenciesAndMeanNormals()
void getConsistenciesAndMeanNormals (TriMesh & mesh, vector< vector< TriMesh::FaceHandle > > & all_guided_neighbors, vector< num_t > & face_areas, vector< TriMesh::Normal > & normals, vector< pair< num_t, TriMesh::Normal > > & consistencies_and_mean_normals)
getConsistenciesAndMeanNormals - consistency and mean normal computation for all patches
Parameters
mesh input mesh
all_guided_neighbors all neighborhoods defining the patches
face_areas all face areas
normals all face normals
consistencies_and_mean_normals output vector containing the consistency and mean normal of all patches
Definition at line 399 of file denoising.cpp.
References getFaceNeighborsInnerEdges(), and NormalDistance().
Referenced by getGuidedNormals().
 {
     const num_t epsilon = 1.0e-9f;
     for (TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         int index = f_it->idx();
         vector<TriMesh::FaceHandle> face_neighbors = all_guided_neighbors[index];
         num_t metric = 0.0f;
         TriMesh::Normal average_normal(0.0f, 0.0f, 0.0f);
         num_t maxdiff = -1.0f;
         for (int i = 0; i < (int)face_neighbors.size(); i++)
         {
             int index_i = face_neighbors[i].idx();
             num_t area_weight = face_areas[index_i];
             TriMesh::Normal ni = normals[index_i];
             average_normal += ni * area_weight;
             for (int j = i + 1; j < (int)face_neighbors.size(); j++)
             {
                 int index_j = face_neighbors[j].idx();
                 TriMesh::Normal nj = normals[index_j];
                 num_t diff = NormalDistance(ni, nj);
                 if (diff > maxdiff)
                 {
                     maxdiff = diff;
                 }
             }
         }
         vector<TriMesh::EdgeHandle> inner_edge_handles;
         getFaceNeighborsInnerEdges(mesh, face_neighbors, inner_edge_handles);
         num_t sum_tv = 0.0, max_tv = -1.0;
         for (int i = 0; i < (int)inner_edge_handles.size(); i++)
         {
             TriMesh::HalfedgeHandle heh = mesh.halfedge_handle(inner_edge_handles[i], 0);
             TriMesh::FaceHandle f = mesh.face_handle(heh);
             TriMesh::Normal n1 = normals[f.idx()];
             TriMesh::HalfedgeHandle heho = mesh.opposite_halfedge_handle(heh);
             TriMesh::FaceHandle fo = mesh.face_handle(heho);
             TriMesh::Normal n2 = normals[fo.idx()];
             num_t current_tv = NormalDistance(n1, n2);
             max_tv = (current_tv > max_tv) ? current_tv : max_tv;
             sum_tv += current_tv;
         }
         average_normal.normalize_cond();
         metric = maxdiff * max_tv / (sum_tv + epsilon);
         consistencies_and_mean_normals[index] = make_pair(metric, average_normal);
     }
 }
getFaceNeighbors_EdgeBased()
void getFaceNeighbors_EdgeBased (TriMesh & mesh, TriMesh::FaceHandle fh, vector< TriMesh::FaceHandle > & face_neighbors)
Face neighborhood.
getFaceNeighbors_EdgeBased: get neighboring faces based on face edges
Parameters
mesh input mesh
fh evaluated face
face_neighbors vector containing neighbors (output)
Definition at line 99 of file neighborhood.cpp.
Referenced by getAllFaceNeighbors_EdgeBased().
 {
     face_neighbors.clear();
     for(TriMesh::FaceFaceIter ff_it = mesh.ff_iter(fh); ff_it.is_valid(); ff_it++)
         face_neighbors.push_back(*ff_it);
 }
getFaceNeighbors_RadiusBased()
void getFaceNeighbors_RadiusBased (TriMesh & mesh, TriMesh::FaceHandle fh, num_t radius, vector< TriMesh::FaceHandle > & face_neighbors)
getFaceNeighbors_RadiusBased: get neighboring faces regarding a radius
Parameters
mesh input mesh
fh evaluated face
radius radius
face_neighbors vector containing neighbors (output)
Definition at line 124 of file neighborhood.cpp.
References getFaceNeighbors_VertexBased().
Referenced by getAllFaceNeighborsGMNF().
 {
     TriMesh::Point ci = mesh.calc_face_centroid(fh);
     vector<bool> flag((int)mesh.n_faces(), false);
     face_neighbors.clear();
     flag[fh.idx()] = true;
     queue<TriMesh::FaceHandle> queue_face_handle;
     queue_face_handle.push(fh);
     vector<TriMesh::FaceHandle> temp_face_neighbors;
     while(!queue_face_handle.empty())
     {
         TriMesh::FaceHandle temp_face_handle_queue = queue_face_handle.front();
         if(temp_face_handle_queue != fh)
             face_neighbors.push_back(temp_face_handle_queue);
         queue_face_handle.pop();
         getFaceNeighbors_VertexBased(mesh, temp_face_handle_queue, temp_face_neighbors);
         for(int i = 0; i < (int)temp_face_neighbors.size(); i++)
         {
             TriMesh::FaceHandle temp_face_handle = temp_face_neighbors[i];
             if(!flag[temp_face_handle.idx()])
             {
                 TriMesh::Point cj = mesh.calc_face_centroid(temp_face_handle);
                 num_t distance = (ci - cj).length();
                 if(distance <= radius)
                     queue_face_handle.push(temp_face_handle);
                 flag[temp_face_handle.idx()] = true;
             }
         }
     }
 }
getFaceNeighbors_VertexBased()
void getFaceNeighbors_VertexBased (TriMesh & mesh, TriMesh::FaceHandle fh, vector< TriMesh::FaceHandle > & face_neighbors)
getFaceNeighbors_VertexBased: get neighboring faces based on face vertices
Parameters
mesh input mesh
fh evaluated face
face_neighbors vector containing neighbors (output)
Definition at line 106 of file neighborhood.cpp.
Referenced by getAllFaceNeighbors_VertexBased(), getAllFaceNeighborsGMNF(), getAllGuidedNeighborsGMNF(), and getFaceNeighbors_RadiusBased().
 {
     face_neighbors.clear();
     set<int> neighbor_face_index; neighbor_face_index.clear();
     for(TriMesh::FaceVertexIter fv_it = mesh.fv_begin(fh); fv_it.is_valid(); fv_it++)
     {
         for(TriMesh::VertexFaceIter vf_it = mesh.vf_iter(*fv_it); vf_it.is_valid(); vf_it++)
         {
             if((*vf_it) != fh)
                 neighbor_face_index.insert(vf_it->idx());
         }
     }
     for(set<int>::iterator iter = neighbor_face_index.begin(); iter != neighbor_face_index.end(); ++ iter)
     {
         face_neighbors.push_back(TriMesh::FaceHandle(*iter));
     }
 }
getFaceNeighborsInnerEdges()
void getFaceNeighborsInnerEdges (TriMesh & mesh, vector< TriMesh::FaceHandle > & face_neighbors, vector< TriMesh::EdgeHandle > & inner_edges)
getFaceNeighborsInnerEdges - get all inner edges of a face neighborhood
Parameters
mesh input mesh
face_neighbors face neighborhood
inner_edges output vector containing all inner edges
Definition at line 372 of file denoising.cpp.
Referenced by getConsistenciesAndMeanNormals().
 {
     inner_edges.clear();
     vector<bool> edge_flags((int)mesh.n_edges(), false);
     vector<bool> face_flags((int)mesh.n_faces(), false);
     for (int i = 0; i < (int)face_neighbors.size(); i++)
         face_flags[face_neighbors[i].idx()] = true;
     for (int i = 0; i < (int)face_neighbors.size(); i++)
     {
         for (TriMesh::FaceEdgeIter fe_it = mesh.fe_iter(face_neighbors[i]); fe_it.is_valid(); fe_it++)
         {
             if ((!edge_flags[fe_it->idx()]) && (!mesh.is_boundary(*fe_it)))
             {
                 edge_flags[fe_it->idx()] = true;
                 TriMesh::HalfedgeHandle heh = mesh.halfedge_handle(*fe_it, 0);
                 TriMesh::FaceHandle f = mesh.face_handle(heh);
                 TriMesh::HalfedgeHandle heho = mesh.opposite_halfedge_handle(heh);
                 TriMesh::FaceHandle fo = mesh.face_handle(heho);
                 if (face_flags[f.idx()] && face_flags[fo.idx()])
                     inner_edges.push_back(*fe_it);
             }
         }
     }
 }
getFaceVertexAngle()
void getFaceVertexAngle (TriMesh & mesh, TriMesh::FaceHandle fh, TriMesh::VertexHandle vh, num_t & angle)
getFaceVertexAngle - angle computation for a given vertex included in a face
Parameters
mesh input mesh
fh corresponding face handle
vh corresponding vertex handle
angle angle
Definition at line 97 of file util.cpp.
 {
     TriMesh::FaceVertexIter verts = mesh.fv_iter(fh);
     TriMesh::VertexHandle vh1,vh2;
     if (vh == *verts)
     {
         vh1 = *(++verts);
         vh2 = *(++verts);
     }
     else
     {
         vh1 = *verts;
         vh2 = (vh == *(++verts)) ? *(++verts) : *verts;
     }
     TriMesh::Point v1 = mesh.point(vh) - mesh.point(vh1);
     TriMesh::Point v2 = mesh.point(vh) - mesh.point(vh2);
     TriMesh::Point v3 = (mesh.point(vh1) - mesh.point(vh2));
     v1.normalize_cond(); v2.normalize_cond();
     angle = acos(v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2]);
 }
getGuidedNormals()
void getGuidedNormals (TriMesh & mesh, vector< vector< TriMesh::FaceHandle > > & all_guided_neighbors, vector< num_t > & face_areas, vector< TriMesh::Normal > & normals, vector< pair< num_t, TriMesh::Normal > > consistencies_and_mean_normals, vector< TriMesh::Normal > & guided_normals)
getGuidedNormals - guided normal computation for each face of the mesh
Parameters
mesh input mesh
all_guided_neighbors all neighborhoods defining the patches
face_areas all face areas
normals all face normals
consistencies_and_mean_normals consistencies and mean normals of all patches
guided_normals output vector containing guided normals for all faces
Definition at line 455 of file denoising.cpp.
References getConsistenciesAndMeanNormals().
Referenced by updateFilteredNormalsGuided().
 {
     getConsistenciesAndMeanNormals(mesh, all_guided_neighbors, face_areas, normals, consistencies_and_mean_normals);
     for (TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         vector<TriMesh::FaceHandle> face_neighbors = all_guided_neighbors[f_it->idx()];
         num_t min_consistency = 1.0e8f;
         int min_idx = 0;
         for (int i = 0; i < (int)face_neighbors.size(); i++)
         {
             num_t current_consistency = consistencies_and_mean_normals[face_neighbors[i].idx()].first;
             if (min_consistency > current_consistency){
                 min_consistency = current_consistency;
                 min_idx = i;
             }
         }
         TriMesh::FaceHandle min_face_handle = face_neighbors[min_idx];
         guided_normals[f_it->idx()] = consistencies_and_mean_normals[min_face_handle.idx()].second;
     }
 }
getRadius()
num_t getRadius (TriMesh & mesh, num_t scalar)
getRadius - computation of radius for radius-based face neighborhood, based on the average of face centroid distances (only between adjacent faces) and multiplied by a scalar
Parameters
mesh input mesh
scalar
Returns
radius value
Definition at line 71 of file denoising.cpp.
References getAllFaceCentroids().
Referenced by updateFilteredNormalsGuided().
 {
     vector<TriMesh::Point> centroids;
     getAllFaceCentroids(mesh, centroids);
     num_t radius = 0.0f;
     num_t num = 0.0f;
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         TriMesh::Point fi = centroids[f_it->idx()];
         for(TriMesh::FaceFaceIter ff_it = mesh.ff_iter(*f_it); ff_it.is_valid(); ff_it++)
         {
             TriMesh::Point fj = centroids[ff_it->idx()];
             radius += (fj - fi).length();
             num++;
         }
     }
     return radius * scalar / num;
 }
getSigmaC()
num_t getSigmaC (TriMesh & mesh, vector< TriMesh::Point > & face_centroids, num_t sigma_c_scalar)
getSigmaC - sigma_c computation based on the average of face centroid distances (only between adjacent faces), and multiplied by a scalar
Parameters
mesh input mesh
face_centroids precomputed face centroids
sigma_c_scalar scalar
Returns
value of sigma_c
Definition at line 53 of file denoising.cpp.
Referenced by updateFilteredNormals(), and updateFilteredNormalsGuided().
 {
     num_t sigma_c = 0.0f;
     num_t num = 0.0f;
     for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
     {
         TriMesh::Point ci = face_centroids[f_it->idx()];
         for(TriMesh::FaceFaceIter ff_it = mesh.ff_iter(*f_it); ff_it.is_valid(); ff_it++)
         {
             TriMesh::Point cj = face_centroids[ff_it->idx()];
             sigma_c += (ci - cj).length();
             num++;
         }
     }
     sigma_c *= sigma_c_scalar / num;
     return sigma_c;
 }
getVertexArea()
num_t getVertexArea (TriMesh & mesh, TriMesh::VertexHandle vh, vector< num_t > & areas)
getVertexArea - vertex area computation (barycentric area)
Parameters
mesh input mesh
vh input vertex (vertex handle)
areas all precomputed triangle areas
Returns
vertex area
Definition at line 118 of file util.cpp.
Referenced by getAllVertexAreas().
 {
     num_t area_sum = 0.0f;
     for(TriMesh::VertexFaceIter vf_iter = mesh.vf_iter(vh);vf_iter.is_valid();vf_iter++)
         area_sum+=areas[vf_iter->idx()];
     return area_sum*(1.0f/3.0f);
 }
getVertexNeighbors()
void getVertexNeighbors (TriMesh & mesh, TriMesh::VertexHandle vh, int k, vector< TriMesh::VertexHandle > & vertex_neighbors)
Vertex neighborhood.
getVertexNeighbors: get all neighboring vertices of a given vertex regarding a depth k (k-ring)
Parameters
mesh input mesh
vh evaluated vertex
k depth
vertex_neighbors vector containing neighbors (output)
Definition at line 7 of file neighborhood.cpp.
Referenced by getAllVertexNeighbors(), myMainWindow::getSelection(), HCLaplacian(), and uniformLaplacian().
 {
     vertex_neighbors.clear();
     vector<bool> mark(mesh.n_vertices(),false);
     queue<TriMesh::VertexHandle> queue_vertex_handle;
     queue<int> queue_depth_handle;
     mark[vh.idx()] = true;
     queue_vertex_handle.push(vh);
     queue_depth_handle.push(0);
     TriMesh::Point ci = mesh.point(vh);
     while(!queue_vertex_handle.empty())
     {
         TriMesh::VertexHandle vh = queue_vertex_handle.front();
         int current_depth = queue_depth_handle.front();
         vertex_neighbors.push_back(vh);
         queue_vertex_handle.pop();
         queue_depth_handle.pop();
         for(TriMesh::VertexVertexIter vv_it = mesh.vv_iter(vh); vv_it.is_valid(); ++vv_it)
         {
             TriMesh::VertexHandle vh_neighbor = *vv_it;
             if(mark[vh_neighbor.idx()] == false)
             {
                 int new_depth = current_depth + 1;
                 if(new_depth <= k)
                 {
                     queue_vertex_handle.push(vh_neighbor);
                     queue_depth_handle.push(new_depth);
                 }
                 mark[vh_neighbor.idx()] = true;
             }
         }
     }
 }
getVolume()
num_t getVolume (TriMesh & mesh)
getVolume - volume computation of a mesh
Parameters
mesh input mesh
Returns
total area
Definition at line 13 of file util.cpp.
{
     typedef TriMesh::HalfedgeHandle hh_t;
     typedef TriMesh::VertexHandle vh_t;
     typedef TriMesh::Point p_t;
     num_t volume = 0.0f;
     num_t three_inv = 1.0f / 3.0f;
     TriMesh::FaceIter f_it;
     for (f_it = mesh.faces_begin(); f_it != mesh.faces_end(); ++f_it)
     {
         hh_t hh = mesh.halfedge_handle(*f_it);
         hh_t hhn = mesh.next_halfedge_handle(hh);
         vh_t v0(mesh.from_vertex_handle(hh));
         vh_t v1(mesh.to_vertex_handle(hh));
         vh_t v2(mesh.to_vertex_handle(hhn));
         p_t p0(mesh.point(v0));
         p_t p1(mesh.point(v1));
         p_t p2(mesh.point(v2));
         p_t g = (p0 + p1 + p2) * three_inv;
         p_t n = (p1 - p0) % (p2 - p0);
         volume += (g|n);
     }
     volume *= 1.0f / 6.0f;
     return volume;
 }
guided()
TriMesh guided (TriMesh _mesh, int normal_iteration_number, int vertex_iteration_number, num_t sigma_c_scalar, num_t sigma_s, num_t radius_scalar)
guided - Denoise the input mesh using Guided Mesh Normal Filtering Algorithm
Parameters
_mesh input mesh
normal_iteration_number number of iterations for normal field filtering
vertex_iteration_number number of iterations for vertex updating
sigma_c_scalar bilateral normal field filtering influence regarding a based on average edge length (spatial distance influence)
sigma_s bilateral normal field filtering parameter
radius_scalar average radius ratio for face neighborhood computation
Returns
denoised mesh
Definition at line 531 of file denoising.cpp.
References updateFilteredNormalsGuided(), and updateVertexPositions().
Referenced by GlobalSmoothingTask::run().
 {
     TriMesh mesh = _mesh;
     if (mesh.n_vertices() == 0)
         return mesh;
     vector<TriMesh::Normal> filtered_normals;
     updateFilteredNormalsGuided(mesh, filtered_normals, radius_scalar, sigma_c_scalar, normal_iteration_number, sigma_s, vertex_iteration_number);
     updateVertexPositions(mesh, filtered_normals, vertex_iteration_number, true);
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
HCLaplacian() [1/2]
TriMesh HCLaplacian (TriMesh & _mesh, int iteration_number, num_t alpha, num_t beta)
HC Laplacian smoothing (Vollmer et al.)
HCLaplacian - denoise the input mesh using HC Laplacian Smoothing Algorithm
Parameters
_mesh input mesh
iteration_number number of iterations
alpha alpha defined in HC Laplacian Smoothing paper
beta beta defined in HC Laplacian Smoothing paper
Returns
denoised mesh
Definition at line 161 of file denoising.cpp.
References getAllPoints(), getVertexNeighbors(), and hasIND().
Referenced by myMainWindow::selectAndSmooth().
 {
     TriMesh mesh = _mesh;
     vector<TriMesh::Point> original_points;
     getAllPoints(mesh,original_points);
     TriMesh temp_mesh_p;
     vector<TriMesh::Point> temp_points_p(original_points);
     vector<TriMesh::Point> uniform_displacement_points;
     uniform_displacement_points.resize(mesh.n_vertices());
     for(int iter = 0; iter < iteration_number; iter++)
     {
         vector<TriMesh::Point> temp_points_q(temp_points_p);
         for (TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
         {
             vector<TriMesh::VertexHandle> vertex_neighbors;
             getVertexNeighbors(_mesh, *v_it, 1, vertex_neighbors);
             if (vertex_neighbors.size()>0)
             {
                 num_t weight = 1.0f / ((num_t)vertex_neighbors.size());
                 TriMesh::Point sum(0.0f, 0.0f, 0.0f);
                 for (int i = 0; i<(int)(vertex_neighbors.size()); i++)
                     sum = sum + ((mesh.point(vertex_neighbors[i]) - mesh.point(*v_it))*weight);
                 uniform_displacement_points[v_it->idx()] = sum;
                 temp_points_p[v_it->idx()] += sum;
             }
             else
                 uniform_displacement_points[v_it->idx()] = TriMesh::Point(0,0,0);
         }
         for (TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
             temp_points_p[v_it->idx()]=uniform_displacement_points[v_it->idx()] + mesh.point(*v_it);
         vector<TriMesh::Point> temp_points_b(temp_points_p.size());
         for(size_t i = 0;i<temp_points_p.size();i++)
             temp_points_b[i]=temp_points_p[i]-(original_points[i]*alpha+(1.0f-alpha)*temp_points_q[i]);
         for(TriMesh::VertexIter v_it = mesh.vertices_begin();v_it!=mesh.vertices_end();v_it++)
         {
             TriMesh::Point t_sum(0,0,0);
             num_t num = 0;
             for(TriMesh::VertexVertexIter vv_it = mesh.vv_iter(*v_it);vv_it.is_valid();vv_it++,num+=1.0f)
                 t_sum+=temp_points_b[vv_it->idx()];
             TriMesh::Point disp = (beta*temp_points_b[v_it->idx()] + ((1.0f - beta) / num)*t_sum);
             if (!hasIND(disp))
                 temp_points_p[v_it->idx()]=temp_points_p[v_it->idx()]-disp;
         }
     }
     for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
         mesh.set_point(*v_it, temp_points_p[v_it->idx()]);
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
HCLaplacian() [2/2]
TriMesh HCLaplacian (TriMesh & _mesh, int iteration_number, num_t alpha, num_t beta, vector< size_t > & vertex_ids)
HCLaplacian - denoise a subset of vertices of an input mesh using HC Laplacian Smoothing Algorithm.
Parameters
_mesh input mesh
iteration_number number of iterations
alpha alpha defined in HC Laplacian Smoothing paper
beta beta defined in HC Laplacian Smoothing paper
vertex_ids subset of vertex IDs to be denoised
Returns
denoised mesh (taking into account only the subset of IDs)
Definition at line 214 of file denoising.cpp.
References getAllPoints(), getVertexNeighbors(), and hasIND().
 {
     TriMesh mesh = _mesh;
     vector<TriMesh::Point> original_points;
     getAllPoints(mesh, original_points);
     TriMesh temp_mesh_p;
     vector<TriMesh::Point> temp_points_p(original_points);
     vector<TriMesh::Point> uniform_displacement_points;
     uniform_displacement_points.resize(mesh.n_vertices());
     for (int iter = 0; iter < iteration_number; iter++)
     {
         vector<TriMesh::Point> temp_points_q(temp_points_p);
         for (size_t i = 0; i < vertex_ids.size(); i++)
         {
             TriMesh::VertexHandle vh((int)vertex_ids[i]);
             vector<TriMesh::VertexHandle> vertex_neighbors;
             getVertexNeighbors(_mesh, vh, 1, vertex_neighbors);
             if (vertex_neighbors.size()>0)
             {
                 num_t weight = 1.0f / ((num_t)vertex_neighbors.size());
                 TriMesh::Point sum(0.0f, 0.0f, 0.0f);
                 for (int i = 0; i<(int)(vertex_neighbors.size()); i++)
                     sum = sum + ((mesh.point(vertex_neighbors[i]) - mesh.point(vh))*weight);
                 uniform_displacement_points[vh.idx()] = sum;
                 temp_points_p[vh.idx()] += sum;
             }
             else
                 uniform_displacement_points[vh.idx()] = TriMesh::Point(0, 0, 0);
         }
         for (size_t i = 0; i < vertex_ids.size(); i++)
         {
             TriMesh::VertexHandle vh((int)vertex_ids[i]);
             temp_points_p[vh.idx()] = uniform_displacement_points[vh.idx()] + mesh.point(vh);
         }
         vector<TriMesh::Point> temp_points_b(temp_points_p.size());
         for (size_t i = 0; i<temp_points_p.size(); i++)
             temp_points_b[i] = temp_points_p[i] - (original_points[i] * alpha + (1.0f - alpha)*temp_points_q[i]);
         for (size_t i = 0; i < vertex_ids.size(); i++)
         {
             TriMesh::VertexHandle vh((int)vertex_ids[i]);
             TriMesh::Point t_sum(0, 0, 0);
             num_t num = 0;
             for (TriMesh::VertexVertexIter vv_it = mesh.vv_iter(vh); vv_it.is_valid(); vv_it++, num += 1.0f)
                 t_sum += temp_points_b[vv_it->idx()];
             TriMesh::Point disp = (beta*temp_points_b[vh.idx()] + ((1.0f - beta) / num)*t_sum);
             if (!hasIND(disp))
                 temp_points_p[vh.idx()] = temp_points_p[vh.idx()] - disp;
         }
     }
     for (size_t i = 0; i < vertex_ids.size(); i++)
     {
         TriMesh::VertexHandle vh((int)vertex_ids[i]);
         mesh.set_point(vh, temp_points_p[vh.idx()]);
     }
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
importMesh()
bool importMesh (TriMesh & mesh, string filename)
importMesh - read mesh file (.obj, .off, .ply, .stl)
Parameters
mesh - output mesh
filename - input file name
Returns
success
Definition at line 3 of file iomesh.cpp.
Referenced by ShapeData::loadFromFile(), and myDataManager::loadInputMesh().
 {
     OpenMesh::IO::Options opt;
     //opt += OpenMesh::IO::Options::VertexColor;
     if(!OpenMesh::IO::read_mesh(mesh, filename, opt))
         return false;
     return true;
 }
NormalDistance()
num_t NormalDistance (const TriMesh::Normal & n1, const TriMesh::Normal & n2) inline
NormalDistance - computation of normal distance: .
Parameters
n1 - input normal 1
n2 - input normal 2
Returns
normal distance
Definition at line 109 of file util.h.
Referenced by getConsistenciesAndMeanNormals().
 {
     return (n1 - n2).length();
 }
uniformLaplacian() [1/2]
TriMesh uniformLaplacian (TriMesh & _mesh, int iteration_number, num_t scale)
Uniform Laplacian smoothing.
uniformLaplacian - denoise the input mesh using Uniform Laplacian Smoothing Algorithm
Parameters
_mesh input mesh
iteration_number number of iterations
scale displacement influence for each iteration
Returns
denoised mesh
Isotropic mesh denoising algorithms
Definition at line 101 of file denoising.cpp.
References getVertexNeighbors().
Referenced by myMainWindow::selectAndSmooth().
 {
     TriMesh mesh = _mesh;
     vector<TriMesh::Point> displacement_points;
     displacement_points.resize(mesh.n_vertices());
     for (int iter = 0; iter < iteration_number; iter++)
     {
         for (TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
         {
             vector<TriMesh::VertexHandle> vertex_neighbors;
             getVertexNeighbors(_mesh, *v_it, 1, vertex_neighbors);
             num_t weight = 1.0f / ((num_t)vertex_neighbors.size());
             TriMesh::Point sum(0.0f, 0.0f, 0.0f);
             for (int i = 0; i<(int)(vertex_neighbors.size()); i++)
                 sum = sum + ((mesh.point(vertex_neighbors[i]) - mesh.point(*v_it))*weight);
             displacement_points[v_it->idx()] = sum;
         }
         for (TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
             mesh.set_point(*v_it, displacement_points[v_it->idx()] * scale + mesh.point(*v_it));
     }
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
uniformLaplacian() [2/2]
TriMesh uniformLaplacian (TriMesh & _mesh, int iteration_number, num_t scale, vector< size_t > & vertex_ids)
uniformLaplacian - denoise a subset of vertices of an input mesh using Uniform Laplacian Smoothing Algorithm
Parameters
_mesh input mesh
iteration_number number of iterations
scale displacement influence for each iteration
vertex_ids subset of vertex IDs to be denoised
Returns
denoised mesh (taking into account only the subset of IDs)
Definition at line 127 of file denoising.cpp.
References getVertexNeighbors().
 {
     TriMesh mesh = _mesh;
     vector<TriMesh::Point> displacement_points;
     displacement_points.resize(mesh.n_vertices());
     for (int iter = 0; iter < iteration_number; iter++)
     {
         for (size_t i = 0; i < vertex_ids.size(); i++)
         {
             TriMesh::VertexHandle vh((int)vertex_ids[i]);
             vector<TriMesh::VertexHandle> vertex_neighbors;
             getVertexNeighbors(_mesh, vh, 1, vertex_neighbors);
             num_t weight = 1.0f / ((num_t)vertex_neighbors.size());
             TriMesh::Point sum(0.0f, 0.0f, 0.0f);
             for (int i = 0; i<(int)(vertex_neighbors.size()); i++)
                 sum = sum + ((mesh.point(vertex_neighbors[i]) - mesh.point(vh))*weight);
             displacement_points[vh.idx()] = sum;
         }
         for (size_t i = 0; i < vertex_ids.size(); i++)
         {
             TriMesh::VertexHandle vh((int)vertex_ids[i]);
             mesh.set_point(vh, displacement_points[vh.idx()] * scale + mesh.point(vh));
         }
     }
     mesh.request_face_normals();
     mesh.request_vertex_normals();
     mesh.update_normals();
     return mesh;
 }
updateFilteredNormals()
void updateFilteredNormals (TriMesh & mesh, int normal_iteration_number, num_t sigma_c_scalar, num_t sigma_s, vector< TriMesh::Normal > & filtered_normals)
Bilateral normal filtering for mesh denoising (Zheng et al.)
updateFilteredNormals - bilateral filtering of the normal field (face based) of a mesh
Parameters
mesh input mesh
normal_iteration_number number of iterations
sigma_c_scalar bilateral filtering influence regarding a based on average edge length (spatial distance influence)
sigma_s bilateral filtering parameter
filtered_normals output vector of filtered face normals
Definition at line 279 of file denoising.cpp.
References GaussianWeight(), getAllFaceAreas(), getAllFaceCentroids(), getAllFaceNeighbors_VertexBased(), getAllFaceNormals(), and getSigmaC().
Referenced by bilateralNormal().
 {
     filtered_normals.resize(mesh.n_faces());
     vector< vector<TriMesh::FaceHandle> > all_face_neighbors;
     getAllFaceNeighbors_VertexBased(mesh,0,all_face_neighbors);
     vector<TriMesh::Normal> previous_normals;
     getAllFaceNormals(mesh, previous_normals);
     vector<num_t> face_areas;
     getAllFaceAreas(mesh, face_areas);
     vector<TriMesh::Point> face_centroids;
     getAllFaceCentroids(mesh, face_centroids);
     num_t sigma_c = getSigmaC(mesh, face_centroids, sigma_c_scalar);
     for(int it = 0; it < normal_iteration_number; it++)
     {
         for(TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
         {
             int face_idx = f_it->idx();
             TriMesh::Normal ni = previous_normals[face_idx];
             TriMesh::Point ci = face_centroids[face_idx];
             vector<TriMesh::FaceHandle> face_neighbors = all_face_neighbors[face_idx];
             TriMesh::Normal temp_normal(0.0, 0.0, 0.0);
             num_t weight_sum = 0.0;
             for (int i = 0; i < (int)face_neighbors.size(); i++)
             {
                 int neighbor_idx = face_neighbors[i].idx();
                 TriMesh::Normal nj = previous_normals[neighbor_idx];
                 TriMesh::Point cj = face_centroids[neighbor_idx];
                 num_t spatial_distance = (ci - cj).length();
                 num_t spatial_weight = GaussianWeight(spatial_distance,sigma_c);
                 num_t range_distance = (ni - nj).length();
                 num_t range_weight = GaussianWeight(range_distance,sigma_s);
                 num_t weight = face_areas[neighbor_idx] * spatial_weight * range_weight;
                 weight_sum += weight;
                 temp_normal += nj * weight;
             }
             temp_normal /= weight_sum;
             temp_normal.normalize_cond();
             filtered_normals[face_idx] = temp_normal;
         }
         previous_normals = filtered_normals;
     }
 }
updateFilteredNormalsGuided()
void updateFilteredNormalsGuided (TriMesh & mesh, vector< TriMesh::Normal > & filtered_normals, num_t radius_scalar, num_t sigma_c_scalar, int normal_iteration_number, num_t sigma_s, int vertex_iteration_number)
updateFilteredNormalsGuided - guided bilateral filtering of a normal field (face based) of a mesh
Parameters
mesh input mesh
filtered_normals guided normals for each face
radius_scalar average radius ratio for face neighborhood computation
sigma_c_scalar bilateral filtering influence regarding a based on average edge length (spatial distance influence)
normal_iteration_number number of iterations for normal field filtering
sigma_s bilateral filtering parameter
vertex_iteration_number number of iterations for vertex updating
Definition at line 480 of file denoising.cpp.
References GaussianWeight(), getAllFaceAreas(), getAllFaceCentroids(), getAllFaceNeighborsGMNF(), getAllFaceNormals(), getAllGuidedNeighborsGMNF(), getGuidedNormals(), getRadius(), getSigmaC(), kRadiusBased, and updateVertexPositions().
Referenced by guided().
 {
     filtered_normals.resize((int)mesh.n_faces());
     bool include_central_face = 1;
     FaceNeighborType face_neighbor_type = kRadiusBased;
     num_t radius;
     radius = getRadius(mesh, radius_scalar);
     vector<vector<TriMesh::FaceHandle> > all_face_neighbors((int)mesh.n_faces());
     getAllFaceNeighborsGMNF(mesh, face_neighbor_type, radius, include_central_face, all_face_neighbors);
     vector<vector<TriMesh::FaceHandle> > all_guided_neighbors((int)mesh.n_faces());
     getAllGuidedNeighborsGMNF(mesh, all_guided_neighbors);
     getAllFaceNormals(mesh, filtered_normals);
     vector<num_t> face_areas((int)mesh.n_faces());
     vector<TriMesh::Point> face_centroids((int)mesh.n_faces());
     vector<TriMesh::Normal> previous_normals((int)mesh.n_faces());
     vector<TriMesh::Normal> guided_normals((int)mesh.n_faces());
     vector<pair<num_t, TriMesh::Normal> > consistencies_and_mean_normals((int)mesh.n_faces());
     for (int iter = 0; iter < normal_iteration_number; iter++)
     {
         getAllFaceCentroids(mesh, face_centroids);
         num_t sigma_c = getSigmaC(mesh, face_centroids, sigma_c_scalar);
         getAllFaceAreas(mesh, face_areas);
         getAllFaceNormals(mesh, previous_normals);
         getGuidedNormals(mesh, all_guided_neighbors, face_areas, previous_normals, consistencies_and_mean_normals, guided_normals);
         for (TriMesh::FaceIter f_it = mesh.faces_begin(); f_it != mesh.faces_end(); f_it++)
         {
             int index = f_it->idx();
             const vector<TriMesh::FaceHandle> face_neighbors = all_face_neighbors[index];
             TriMesh::Normal filtered_normal(0.0f, 0.0f, 0.0f);
             for (int j = 0; j < (int)face_neighbors.size(); j++)
             {
                 int current_face_index = face_neighbors[j].idx();
                 num_t spatial_dis = (face_centroids[index] - face_centroids[current_face_index]).length();
                 num_t spatial_weight = GaussianWeight(spatial_dis, sigma_c);
                 num_t range_dis = (guided_normals[index] - guided_normals[current_face_index]).length();
                 num_t range_weight = GaussianWeight(range_dis, sigma_s);
                 filtered_normal += previous_normals[current_face_index] * (face_areas[current_face_index] * spatial_weight * range_weight);
             }
             if (face_neighbors.size())
                 filtered_normals[index] = filtered_normal.normalize_cond();
         }
         updateVertexPositions(mesh, filtered_normals, vertex_iteration_number, false);
     }
 }
updateVertexPositions()
void updateVertexPositions (TriMesh & mesh, vector< TriMesh::Normal > & filtered_normals, int iteration_number, bool fixed_boundary)
updateVertexPositions - computes new vertex positions adapted to an input normal field.
Parameters
mesh input mesh.
filtered_normals input normal field.
iteration_number number of iterations of the optimization algorithm (gradient descent approach).
fixed_boundary determines if a boundary vertex will be updated
Definition at line 14 of file denoising.cpp.
References getAllFaceCentroids(), and hasIND().
Referenced by bilateralNormal(), guided(), and updateFilteredNormalsGuided().
 {
     vector<TriMesh::Point> new_points(mesh.n_vertices());
     vector<TriMesh::Point> centroids;
     for(int iter = 0; iter < iteration_number; iter++)
     {
         getAllFaceCentroids(mesh, centroids);
         for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
         {
             TriMesh::Point p = mesh.point(*v_it);
             if(fixed_boundary && mesh.is_boundary(*v_it))
             {
                 new_points.at(v_it->idx()) = p;
             }
             else
             {
                 num_t face_num = 0.0f;
                 TriMesh::Point temp_point(0.0f, 0.0f, 0.0f);
                 for(TriMesh::VertexFaceIter vf_it = mesh.vf_iter(*v_it); vf_it.is_valid(); vf_it++)
                 {
                     TriMesh::Normal temp_normal = filtered_normals[vf_it->idx()];
                     TriMesh::Point temp_centroid = centroids[vf_it->idx()];
                     temp_point += temp_normal * (temp_normal | (temp_centroid - p));
                     face_num++;
                 }
                 p += temp_point / face_num;
                 if (!hasIND(p))
                 {
                     new_points.at(v_it->idx()) = p;
                 }
                 else new_points.at(v_it->idx()) = p;
             }
         }
         for(TriMesh::VertexIter v_it = mesh.vertices_begin(); v_it != mesh.vertices_end(); v_it++)
             mesh.set_point(*v_it, new_points[v_it->idx()]);
     }
 }