Mesh Smoothing Tool: visualization/myRenderer.cpp File Reference
myRenderer.cpp File Reference
#include "myRenderer.h"
Functions
bool checkStatus (GLuint objectID, PFNGLGETSHADERIVPROC objectPropertyGetterFunc, PFNGLGETSHADERINFOLOGPROC getInfoLogFunc, GLenum statusType)
bool checkShaderStatus (GLuint shaderID)
bool checkProgramStatus (GLuint programID)
Function Documentation
checkProgramStatus()
bool checkProgramStatus (GLuint programID)
Definition at line 28 of file myRenderer.cpp.
References checkStatus().
Referenced by myRenderer::installShaders().
 {
     return checkStatus(programID, glGetProgramiv, glGetProgramInfoLog, GL_LINK_STATUS);
 }
checkShaderStatus()
bool checkShaderStatus (GLuint shaderID)
Definition at line 23 of file myRenderer.cpp.
References checkStatus().
Referenced by myRenderer::installShaders().
 {
     return checkStatus(shaderID, glGetShaderiv, glGetShaderInfoLog, GL_COMPILE_STATUS);
 }
checkStatus()
bool checkStatus (GLuint objectID, PFNGLGETSHADERIVPROC objectPropertyGetterFunc, PFNGLGETSHADERINFOLOGPROC getInfoLogFunc, GLenum statusType)
Definition at line 5 of file myRenderer.cpp.
Referenced by checkProgramStatus(), and checkShaderStatus().
 {
     GLint status;
     objectPropertyGetterFunc(objectID, statusType, &status);
     if (status != GL_TRUE)
     {
         GLint infoLogLength;
         objectPropertyGetterFunc(objectID, GL_INFO_LOG_LENGTH, &infoLogLength);
         GLchar * buffer = new GLchar[infoLogLength];
         GLsizei bufferSize;
         getInfoLogFunc(objectID, infoLogLength, &bufferSize, buffer);
         cout << buffer << endl;
         delete[] buffer;
         return false;
     }
     return true;
 }