Mesh Smoothing Tool: ShapeData Struct Reference
ShapeData Struct Reference
Visualization based in OpenGL
The ShapeData struct - triangular mesh for OpenGL buffers manipulation.
#include <myShape.h>
Public Member Functions
ShapeData ()
ShapeData - default constructor.
ShapeData (string fileName)
ShapeData - generates shape data using a triangular mesh file supported in OpenMesh library.
void loadFromFile (string fileName)
loadFromFile - load shape data using a triangular mesh file supported in OpenMesh library
void loadMesh (TriMesh &_mesh)
loadMesh - load shape data from a data structure defined in OpenMesh library
void loadMeshVertexSelection (TriMesh &_mesh, vector< size_t > &selected_vertices)
loadMeshVertexSelection - load as shape data a subset of vertices (only vertices) from a data structure defined in OpenMesh library
GLsizeiptr vertexBufferSize () const
vertexBufferSize - get size of the array of vertices
GLsizeiptr indexBufferSize () const
indexBufferSize - get size of the array of indices
void clear ()
clear - erase arrays and reinitialize values
Data Fields
GLuint numVertices
numVertices - number of vertices of the mesh
GLuint numIndices
numIndices - number of indices of all triangles
Vertex * vertices
vertices - array containing all vertices
GLuint * indices
indices - array containing all indices
glm::vec3 centroid
centroid - shape centroid
Detailed Description
The ShapeData struct - triangular mesh for OpenGL buffers manipulation.
Definition at line 36 of file myShape.h.
Constructor & Destructor Documentation
ShapeData() [1/2]
ShapeData::ShapeData () inline
ShapeData - default constructor.
Definition at line 64 of file myShape.h.
 :vertices(0), numVertices(0),indices(0), numIndices(0){}
ShapeData() [2/2]
ShapeData::ShapeData (string fileName) inline
ShapeData - generates shape data using a triangular mesh file supported in OpenMesh library.
Parameters
fileName - mesh file name
Definition at line 69 of file myShape.h.
     {
         loadFromFile(fileName);
     }
Member Function Documentation
clear()
void ShapeData::clear () inline
clear - erase arrays and reinitialize values
Definition at line 174 of file myShape.h.
Referenced by myDataManager::loadInputMesh(), myDataManager::updateInputShape(), myDataManager::updateOutputSelection(), myDataManager::updateOutputShape(), and myDataManager::~myDataManager().
     {
         delete[] vertices;
         delete[] indices;
         vertices = 0;
         indices = 0;
         numVertices = numIndices = 0;
         centroid = glm::vec3(0.0f,0.0f,0.0f);
     }
indexBufferSize()
GLsizeiptr ShapeData::indexBufferSize () const inline
indexBufferSize - get size of the array of indices
Returns
- size of array of indices
Definition at line 167 of file myShape.h.
     {
         return numIndices * sizeof(GLuint);
     }
loadFromFile()
void ShapeData::loadFromFile (string fileName) inline
loadFromFile - load shape data using a triangular mesh file supported in OpenMesh library
Parameters
fileName - mesh file name
Definition at line 77 of file myShape.h.
References importMesh().
     {
         TriMesh _mesh;
         importMesh(_mesh, fileName);
         _mesh.request_face_normals();
         _mesh.request_vertex_normals();
         _mesh.update_normals();
         loadMesh(_mesh);
     }
loadMesh()
void ShapeData::loadMesh (TriMesh & _mesh) inline
loadMesh - load shape data from a data structure defined in OpenMesh library
Parameters
_mesh - triangular mesh
Definition at line 90 of file myShape.h.
References Vertex::color, Vertex::normal, and Vertex::position.
Referenced by myDataManager::updateInputShape(), and myDataManager::updateOutputShape().
     {
         numVertices = static_cast<GLuint>(_mesh.n_vertices());
         vertices = new Vertex[numVertices];
         numIndices = static_cast<GLuint>(_mesh.n_faces() * 3);
         indices = new GLuint[numIndices];
         GLuint currentIndex = 0;
         TriMesh::Point c(0, 0, 0);
         float n = 0.0f;
         for (TriMesh::VertexIter v_it = _mesh.vertices_begin(); v_it != _mesh.vertices_end(); v_it++)
         {
             TriMesh::Color current_color = _mesh.color(*v_it);
             TriMesh::Point current_point = _mesh.point(*v_it);
             TriMesh::Normal current_normal = _mesh.normal(*v_it);
             c += current_point;
             n++;
             vertices[currentIndex].position = glm::vec3(current_point[0], current_point[1], current_point[2]);
             vertices[currentIndex].color = glm::vec3(0.5f, 0.5f, 0.5f);
             vertices[currentIndex].normal = glm::vec3(current_normal[0], current_normal[1], current_normal[2]);
             currentIndex++;
         }
         c = c / n;
         centroid[0] = c[0];
         centroid[1] = c[1];
         centroid[2] = c[2];
         currentIndex = 0;
         for (TriMesh::FaceIter f_it = _mesh.faces_begin(); f_it != _mesh.faces_end(); f_it++)
         {
             for (TriMesh::FaceVertexIter fv_it = _mesh.fv_iter(*f_it); fv_it.is_valid(); fv_it++)
             {
                 indices[currentIndex] = static_cast<GLuint>(fv_it->idx());
                 currentIndex++;
             }
         }
     }
loadMeshVertexSelection()
void ShapeData::loadMeshVertexSelection (TriMesh & _mesh, vector< size_t > & selected_vertices) inline
loadMeshVertexSelection - load as shape data a subset of vertices (only vertices) from a data structure defined in OpenMesh library
Parameters
_mesh - triangular mesh
selected_vertices - subset of vertices ids of _mesh
Definition at line 131 of file myShape.h.
References Vertex::color, Vertex::normal, and Vertex::position.
Referenced by myDataManager::updateOutputSelection().
     {
         numVertices = static_cast<GLuint>(_mesh.n_vertices());
         vertices = new Vertex[numVertices];
         numIndices = 0;
         indices = new GLuint[numIndices];
         TriMesh::Point c(0, 0, 0);
         float n = 0.0f;
         for (size_t i = 0; i < selected_vertices.size(); i++)
         {
             TriMesh::VertexHandle vh((int)selected_vertices[i]);
             TriMesh::Point current_point = _mesh.point(vh);
             TriMesh::Normal current_normal = _mesh.normal(vh);
             c += current_point;
             n++;
             vertices[i].position = glm::vec3(current_point[0], current_point[1], current_point[2]);
             vertices[i].color = glm::vec3(1.0f, 0.0f, 0.0f);
             vertices[i].normal = glm::vec3(current_normal[0], current_normal[1], current_normal[2]);
         }
         c = c / n;
         centroid[0] = c[0];
         centroid[1] = c[1];
         centroid[2] = c[2];
     }
vertexBufferSize()
GLsizeiptr ShapeData::vertexBufferSize () const inline
vertexBufferSize - get size of the array of vertices
Returns
- size of array of vertices
Definition at line 159 of file myShape.h.
     {
         return numVertices * sizeof(Vertex);
     }
Field Documentation
centroid
glm::vec3 ShapeData::centroid
centroid - shape centroid
Definition at line 59 of file myShape.h.
indices
GLuint* ShapeData::indices
indices - array containing all indices
Definition at line 54 of file myShape.h.
numIndices
GLuint ShapeData::numIndices
numIndices - number of indices of all triangles
Definition at line 45 of file myShape.h.
numVertices
GLuint ShapeData::numVertices
numVertices - number of vertices of the mesh
Definition at line 41 of file myShape.h.
vertices
Vertex* ShapeData::vertices
vertices - array containing all vertices
Definition at line 50 of file myShape.h.
The documentation for this struct was generated from the following file:
visualization/myShape.h